from pathlib import Path
p=Path('src/DmpMedicationCalculator.tsx')
s=p.read_text(); original=s

def once(old,new,label):
    global s
    if old not in s: raise SystemExit(f'missing {label}')
    s=s.replace(old,new,1)

# Add custom concentration entry state and start already confirmed from the medication-list selection.
once('[route,setRoute]=useState(""),[medConfirmed,setMedConfirmed]=useState(false),[concConfirmed,setConcConfirmed]=useState(false),', '[route,setRoute]=useState(""),[medConfirmed]=useState(true),[concConfirmed,setConcConfirmed]=useState(false),[customConcentrationMode,setCustomConcentrationMode]=useState(false),[customConcentration,setCustomConcentration]=useState(""),', 'confirmation state')

# Use custom field concentration when selected; otherwise Admin/common EMS value.
once('conc=fieldConcentration?concentrationInUnit(fieldConcentration,concentrationUnit):0,eligibilityAge=', 'adminConc=fieldConcentration?concentrationInUnit(fieldConcentration,concentrationUnit):0,conc=customConcentrationMode?Number(customConcentration):adminConc,eligibilityAge=', 'effective concentration')

# Start at concentration when a single-agent med needs concentration; otherwise indication. Multi-agent group still needs agent selection, but never a redundant confirm checkbox.
once('[step,setStep]=useState<Step>("medication"),[path,setPath]=useState<GenericDosePath|null>(null),[selectedAgent,setSelectedAgent]=useState(medicationAgents.length===1?medicationAgents[0]:""),', '[step,setStep]=useState<Step>(()=>medicationAgents.length===1?(medication.paths.some(pathUsesConcentration)?"concentration":"indication"):"medication"),[path,setPath]=useState<GenericDosePath|null>(null),[selectedAgent,setSelectedAgent]=useState(medicationAgents.length===1?medicationAgents[0]:""),', 'initial step')

# Medication is complete because selecting it from the home screen is the confirmation. For grouped multi-agent entries, choosing the agent advances immediately.
once('{id:"medication",label:"MEDICATION",value:selectedAgent||medication.name,detail:medConfirmed?"Physical medication confirmed":"Confirm physical medication",complete:medConfirmed,active:step==="medication",available:true,onClick:()=>setStep("medication")},', '{id:"medication",label:"MEDICATION",value:selectedAgent||medication.name,detail:selectedAgent?"Selected from medication list":"Select medication agent",complete:!!selectedAgent,active:step==="medication",available:true,onClick:()=>medicationAgents.length>1&&setStep("medication")},', 'medication board')

# Concentration board reflects admin or custom selected value.
once('{id:"concentration",label:"CONCENTRATION",value:fieldConcentration?.label|| (conc>0?`${fmt(conc)} ${concentrationUnit}/mL`:""),detail:concConfirmed?"Admin concentration confirmed":"Confirm admin-set concentration",complete:agentNeedsConcentration&&!!fieldConcentration&&concConfirmed,notRequired:!agentNeedsConcentration,active:step==="concentration",available:medConfirmed,onClick:()=>agentNeedsConcentration&&setStep("concentration")},', '{id:"concentration",label:"CONCENTRATION",value:conc>0?(customConcentrationMode?`${fmt(conc)} ${concentrationUnit}/mL • Custom`:fieldConcentration?.label||`${fmt(conc)} ${concentrationUnit}/mL`):"",detail:concConfirmed?(customConcentrationMode?"Custom label confirmed":"Admin concentration selected"):"Select concentration",complete:agentNeedsConcentration&&conc>0&&concConfirmed,notRequired:!agentNeedsConcentration,active:step==="concentration",available:!!selectedAgent,onClick:()=>agentNeedsConcentration&&setStep("concentration")},', 'concentration board')

# Remove redundant medication confirm UI. For grouped entries only, agent selection itself advances.
old='''      {step==="medication"&&<><small className="eyebrow">MEDICATION</small><h1>Confirm the medication in your hand</h1><p className="screen-help">Choose the medication, then confirm that the physical medication matches. Concentration is confirmed on the next screen from the Admin-set value.</p>{medicationAgents.length>1&&<div className="builder-options">{medicationAgents.map(x=><button key={x} className={selectedAgent===x?"selected":""} onClick={()=>{setSelectedAgent(x);setPath(null);setMedConfirmed(false);setConcConfirmed(false)}}><b>{x}</b><span>DMP {medication.protocolId}</span></button>)}</div>}{selectedAgent&&<><div className="versed-med-display"><div className="versed-vial"><span>{selectedAgent}</span><b>Rx</b><small>PHYSICAL MEDICATION</small></div><div><small>SELECTED MEDICATION</small><h2>{selectedAgent}</h2><p>DMP {medication.protocolId}</p></div></div><label className={medConfirmed?"builder-confirm checked":"builder-confirm"}><input type="checkbox" checked={medConfirmed} onChange={e=>setMedConfirmed(e.target.checked)}/><span><b>Medication matches</b>{selectedAgent}</span></label><button className="continue" disabled={!medConfirmed||!selectedAgent} onClick={()=>setStep(agentNeedsConcentration?"concentration":"indication")}>Continue to {agentNeedsConcentration?"concentration":"indication"} <span>→</span></button></>}</>}'''
new='''      {step==="medication"&&<><small className="eyebrow">MEDICATION</small><h1>Select medication agent</h1><p className="screen-help">The medication was already selected on the main screen. Choose the specific agent only when this grouped DMP entry contains more than one medication.</p><div className="builder-options">{medicationAgents.map(x=><button key={x} className={selectedAgent===x?"selected":""} onClick={()=>{setSelectedAgent(x);setPath(null);setConcConfirmed(false);setCustomConcentrationMode(false);setCustomConcentration("");const paths=medication.paths.filter(p=>p.agent===x);setStep(paths.some(pathUsesConcentration)?"concentration":"indication")}}><b>{x}</b><span>DMP {medication.protocolId}</span></button>)}</div></>}'''
once(old,new,'medication UI')

# Replace concentration screen with exactly two choices. Admin/default advances on one tap. Custom reveals entry; confirmation auto-advances, no separate Continue button.
old='''      {step==="concentration"&&<><small className="eyebrow">CONCENTRATION</small><h1>Confirm the concentration</h1><p className="screen-help">This concentration is controlled by Admin. Until Admin changes it, the app uses the common EMS stock concentration already defined for this medication.</p>{fieldConcentration?<><div className="builder-options concentration-options fentanyl-concentration-options"><button type="button" className="selected"><b>{fieldConcentration.label||`${fmt(conc)} ${concentrationUnit}/mL`}</b><span>{fmt(conc)} {concentrationUnit}/mL • Admin/default</span></button></div><label className={concConfirmed?"builder-confirm checked":"builder-confirm"}><input type="checkbox" checked={concConfirmed} onChange={e=>setConcConfirmed(e.target.checked)}/><span><b>Concentration matches the physical label</b>{fieldConcentration.label||`${fmt(conc)} ${concentrationUnit}/mL`}</span></label><button className="continue" disabled={!concConfirmed} onClick={()=>setStep("indication")}>Continue to indication <span>→</span></button></>:<div className="hard-stop"><b>ADMIN CONCENTRATION REQUIRED</b><span>No field concentration is configured for this medication. Admin must set one before this calculator can be used.</span></div>}</>}'''
new='''      {step==="concentration"&&<><small className="eyebrow">CONCENTRATION</small><h1>Select concentration</h1><p className="screen-help">Tap the department concentration if it matches the medication in your hand. Use Custom only when the physical label is different.</p><div className="builder-options concentration-options fentanyl-concentration-options">{fieldConcentration&&<button type="button" className={!customConcentrationMode&&concConfirmed?"selected":""} onClick={()=>{setCustomConcentrationMode(false);setCustomConcentration("");setConcConfirmed(true);setStep("indication")}}><b>{fieldConcentration.label||`${fmt(adminConc)} ${concentrationUnit}/mL`}</b><span>{fmt(adminConc)} {concentrationUnit}/mL • Department/Admin</span></button>}<button type="button" className={customConcentrationMode?"selected":""} onClick={()=>{setCustomConcentrationMode(true);setCustomConcentration("");setConcConfirmed(false)}}><b>Custom</b><span>Physical label is different</span></button></div>{customConcentrationMode&&<div className="builder-custom"><label>Concentration<input autoFocus inputMode="decimal" value={customConcentration} onChange={e=>{setCustomConcentration(e.target.value);setConcConfirmed(false)}} placeholder="0"/><b>{concentrationUnit}/mL</b></label>{Number(customConcentration)>0&&<strong>{fmt(Number(customConcentration))} {concentrationUnit}/mL</strong>}<label className={concConfirmed?"builder-confirm checked":"builder-confirm"}><input type="checkbox" disabled={!(Number(customConcentration)>0)} checked={concConfirmed} onChange={e=>{const checked=e.target.checked;setConcConfirmed(checked);if(checked&&Number(customConcentration)>0)setStep("indication")}}/><span><b>Custom concentration matches physical label</b>{Number(customConcentration)>0?`${fmt(Number(customConcentration))} ${concentrationUnit}/mL`:"Enter the label concentration"}</span></label></div>}{!fieldConcentration&&!customConcentrationMode&&<div className="input-guidance"><b>No department concentration configured</b><span>Choose Custom for this calculation, then have Admin set the department default.</span></div>}</>}'''
once(old,new,'concentration UI')

# Result review medication should return to agent selector only for grouped entries.
once('<button onClick={()=>setStep("medication")}><small>MEDICATION</small><b>{path.agent}</b></button>', '<button onClick={()=>medicationAgents.length>1?setStep("medication"):close()}><small>MEDICATION</small><b>{path.agent}</b></button>', 'result medication edit')

if s==original: raise SystemExit('no changes')
p.write_text(s)
print('streamlined non-Fentanyl field flow')
