"use client";
import { useEffect, useMemo, useState, type ReactNode } from "react";

type Step="drug"|"reason"|"age"|"weight"|"safety"|"vial"|"review";
const steps:Step[]=["drug","reason","age","weight","safety","vial","review"];
const drugs=[
 {id:"fentanyl",name:"Fentanyl",sub:"Opioid analgesic",active:true},
 {id:"midazolam",name:"Midazolam",sub:"Benzodiazepine",active:false},
 {id:"ketorolac",name:"Ketorolac",sub:"Non-opioid analgesic",active:false},
 {id:"epinephrine",name:"Epinephrine",sub:"Multiple concentrations",active:false},
];
const reasons=["Pain management","Sedation for pacing","Sedation for cardioversion"];
const safetyItems=["No known allergy to fentanyl or opioids","Full Denver Metro protocol and indication reviewed","Airway, ventilation, blood pressure and mental status assessed"];

export default function Home(){
 const [step,setStep]=useState<Step>("drug"),[drug,setDrug]=useState(""),[reason,setReason]=useState(""),[age,setAge]=useState(""),[weight,setWeight]=useState(""),[weightUnit,setWeightUnit]=useState("kg"),[route,setRoute]=useState(""),[amount,setAmount]=useState(""),[vialMl,setVialMl]=useState(""),[checks,setChecks]=useState([false,false,false]),[online,setOnline]=useState(true),[installOpen,setInstallOpen]=useState(false);
 useEffect(()=>{setOnline(navigator.onLine);const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[]);
 const kg=weightUnit==="lb"?Number(weight)/2.20462:Number(weight),adult=Number(age)>=12,dosePerKg=1,dose=kg*dosePerKg,concentration=Number(amount)&&Number(vialMl)?Number(amount)/Number(vialMl):0,volume=concentration?dose/concentration:0;
 const visibleSteps=steps,position=visibleSteps.indexOf(step),progress=((position+1)/visibleSteps.length)*100;
 const valid=useMemo(()=>({drug:!!drug,reason:!!reason,age:Number(age)>0&&Number(age)<130,weight:kg>0&&kg<350,safety:checks.every(Boolean),vial:!!route&&Number(amount)>0&&Number(vialMl)>0,review:true}),[drug,reason,age,kg,checks,route,amount,vialMl]);
 const next=()=>{if(!valid[step])return;setStep(visibleSteps[Math.min(position+1,visibleSteps.length-1)])},back=()=>setStep(visibleSteps[Math.max(position-1,0)]),reset=()=>{setStep("drug");setDrug("");setReason("");setAge("");setWeight("");setRoute("");setAmount("");setVialMl("");setChecks([false,false,false])};
 return <main className="wizard-app"><header><div className="brand"><b>M</b><span><strong>Metro Med Dose</strong><small>Guided medication cross-check</small></span></div><div className="header-actions"><span className={`connection ${online?"online":"offline"}`}>{online?"Online":"Offline ready"}</span><button onClick={()=>setInstallOpen(true)}>Install</button></div></header>
 <section className="wizard-shell"><div className="wizard-top"><button className="back" onClick={back} disabled={step==="drug"}>‹ Back</button><span>Step {position+1} of {visibleSteps.length}</span><button className="start-over" onClick={reset}>Start over</button></div><div className="progress"><i style={{width:`${progress}%`}}/></div>
 <div className="clinical-banner"><b>Clinical review build</b><span>Example fentanyl pathway uses the requested 1 mcg/kg training value. Physician approval is required before patient care.</span></div>

 {step==="drug"&&<Screen eyebrow="START" title="Which medication was requested?" help="Select the medication you intend to administer."><div className="choice-grid">{drugs.map(d=><button key={d.id} disabled={!d.active} className={`choice ${drug===d.id?"selected":""}`} onClick={()=>{setDrug(d.id);setTimeout(()=>setStep("reason"),180)}}><span className="rx">Rx</span><span><b>{d.name}</b><small>{d.sub}</small></span>{d.active?<i>›</i>:<em>Pending review</em>}</button>)}</div></Screen>}
 {step==="reason"&&<Screen eyebrow="INDICATION" title="Why is fentanyl being given?" help="The indication controls which protocol dose and routes are available."><div className="stack">{reasons.map(r=><button className={`big-choice ${reason===r?"selected":""}`} key={r} onClick={()=>{setReason(r);setTimeout(()=>setStep("age"),180)}}><span>{r}</span><i>›</i></button>)}</div></Screen>}
 {step==="age"&&<Screen eyebrow="PATIENT" title="Enter the patient’s age" help="Denver Metro generally defines adult as 12 years and older."><label className="giant-input"><span>Age in years</span><input autoFocus inputMode="decimal" placeholder="0" value={age} onChange={e=>setAge(e.target.value)}/></label>{Number(age)>0&&<div className="classification"><span>Protocol category</span><b>{adult?"Adult":"Pediatric"}</b></div>}<Next enabled={valid.age} onClick={next}/></Screen>}
 {step==="weight"&&<Screen eyebrow="WEIGHT-BASED DOSE" title="Enter the calculation weight" help="Use an actual scale weight when available. Confirm pounds versus kilograms."><div className="unit-toggle"><button className={weightUnit==="kg"?"selected":""} onClick={()=>setWeightUnit("kg")}>Kilograms</button><button className={weightUnit==="lb"?"selected":""} onClick={()=>setWeightUnit("lb")}>Pounds</button></div><label className="giant-input"><span>Patient weight ({weightUnit})</span><input autoFocus inputMode="decimal" placeholder="0" value={weight} onChange={e=>setWeight(e.target.value)}/></label>{kg>0&&<div className="classification"><span>Calculation weight</span><b>{fmt(kg)} kg</b></div>}<Next enabled={valid.weight} onClick={next}/></Screen>}
 {step==="safety"&&<Screen eyebrow="SAFETY CHECK" title="Review contraindications and precautions" help="All three checks are required. This screen does not replace the complete protocol."><div className="safety-list">{safetyItems.map((x,i)=><label key={x} className={checks[i]?"checked":""}><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(checks.map((v,n)=>n===i?e.target.checked:v))}/><span><b>{i+1}</b>{x}</span></label>)}</div><a className="protocol-link" href="https://dmemsmd.org/wp-content/uploads/sites/51/2026/07/DMEMSMD-Protocols-July-2026-FINAL-2026-07-20.pdf" target="_blank" rel="noreferrer">Open complete Denver Metro protocol ↗</a><Next enabled={valid.safety} onClick={next}/></Screen>}
 {step==="vial"&&<Screen eyebrow="MEDICATION VERIFICATION" title="Match the vial in your hand" help="Packaging varies. Read the label—never rely on the photo alone."><div className="med-verify"><div className="photo-placeholder"><div className="drawn-vial"><small>FENTANYL</small><b>VIAL</b><small>PHOTO REQUIRED</small></div><span>Department vial photo pending</span></div><div className="dose-card"><small>SELECTED PROTOCOL PATH</small><h3>Fentanyl • {reason}</h3><p><span>Dose</span><b>1 mcg/kg</b></p><p><span>Patient</span><b>{adult?"Adult":"Pediatric"}, {fmt(kg)} kg</b></p></div></div><div className="route-label">Select route</div><div className="route-grid">{["IV/IO","IM","IN"].map(r=><button className={route===r?"selected":""} onClick={()=>setRoute(r)} key={r}>{r}</button>)}</div><h3 className="label-heading">Enter exactly what the vial label says</h3><div className="vial-entry"><label><span>Total drug</span><div><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/><b>mcg</b></div></label><label><span>Total volume</span><div><input inputMode="decimal" value={vialMl} onChange={e=>setVialMl(e.target.value)} placeholder="0"/><b>mL</b></div></label></div>{concentration>0&&<div className="concentration-check"><span>Entered concentration</span><b>{fmt(concentration)} mcg/mL</b></div>}<Next enabled={valid.vial} onClick={next} text="Review final dose"/></Screen>}
 {step==="review"&&<Screen eyebrow="FINAL CROSS-CHECK" title="Confirm the complete medication plan" help="Read from top to bottom before drawing up or administering."><div className="final-card"><div className="final-drug"><span>Medication</span><b>Fentanyl</b><small>{reason} • {route}</small></div><Review label="Patient category" value={`${adult?"Adult":"Pediatric"} • age ${age}`}/><Review label="Calculation weight" value={`${fmt(kg)} kg`}/><Review label="Denver Metro dose" value={`1 mcg/kg`}/><Review label="Dose calculation" value={`${fmt(kg)} kg × 1 mcg/kg = ${fmt(dose)} mcg`}/><Review label="Vial entered" value={`${amount} mcg in ${vialMl} mL`}/><Review label="Concentration" value={`${fmt(concentration)} mcg/mL`}/><Review label="Volume calculation" value={`${fmt(dose)} mcg ÷ ${fmt(concentration)} mcg/mL = ${fmt(volume)} mL`}/><div className="give"><small>CALCULATED DOSE</small><b>{fmt(dose)} mcg</b><small>DRAW UP</small><strong>{fmt(volume)} mL</strong></div></div><div className="final-warning"><b>Verify before administration</b><span>Confirm indication, route, concentration, dose limits and the complete approved protocol with the medication container in hand.</span></div><button className="new-calc" onClick={reset}>Start a new calculation</button></Screen>}
 </section>{installOpen&&<div className="modal-backdrop" onClick={()=>setInstallOpen(false)}><section className="install-modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setInstallOpen(false)}>×</button><b className="app-icon">M</b><h2>Install for offline use</h2><ol><li>Open this page in Safari.</li><li>Tap Share.</li><li>Choose <b>Add to Home Screen</b>.</li><li>Open once online before relying on offline access.</li></ol></section></div>}</main>
}
function Screen({eyebrow,title,help,children}:{eyebrow:string,title:string,help:string,children:ReactNode}){return <section className="wizard-card"><small className="eyebrow">{eyebrow}</small><h1>{title}</h1><p className="screen-help">{help}</p>{children}</section>}
function Next({enabled,onClick,text="Continue"}:{enabled:boolean,onClick:()=>void,text?:string}){return <button className="continue" disabled={!enabled} onClick={onClick}>{text}<span>→</span></button>}
function Review({label,value}:{label:string,value:string}){return <div className="review-row"><span>{label}</span><b>{value}</b></div>}
function fmt(n:number){return Number.isFinite(n)?Number(n.toFixed(2)).toString():"—"}
