"use client";
import {useEffect,useMemo,useState,type ReactNode} from "react";

type Step="drug"|"reason"|"age"|"weight"|"safety"|"vial"|"review";
type Route="IV/IO"|"IM"|"IN";
const PROTOCOL_DATE="July 2026",REVIEW_DATE=new Date("2027-01-01T00:00:00-07:00");
const PROTOCOL_URL="https://dmemsmd.org/wp-content/uploads/sites/51/2026/07/DMEMSMD-Protocols-July-2026-FINAL-2026-07-20.pdf";
const drugs=[
 {id:"fentanyl",name:"Fentanyl",brand:"Sublimaze",sub:"Opioid analgesic",active:true},
 {id:"midazolam",name:"Midazolam",brand:"Versed",sub:"Benzodiazepine",active:false},
 {id:"ketorolac",name:"Ketorolac",brand:"Toradol",sub:"Non-opioid analgesic",active:false},
 {id:"epinephrine",name:"Epinephrine",brand:"Adrenalin",sub:"Multiple concentrations",active:false}
];
const baseSafety=["Patient is hemodynamically stable with NO signs of shock","Patient has NO respiratory depression","Medication, indication and route match the July 2026 DMP","No benzodiazepine coadministration OR direct physician verbal order obtained"];

export default function App(){
 const [step,setStep]=useState<Step>("drug"),[drug,setDrug]=useState(""),[search,setSearch]=useState(""),[reason,setReason]=useState(""),[age,setAge]=useState(""),[weight,setWeight]=useState(""),[weightUnit,setWeightUnit]=useState("kg"),[weightSource,setWeightSource]=useState("actual"),[route,setRoute]=useState<Route|null>(null),[doseRate,setDoseRate]=useState<number|null>(null),[amount,setAmount]=useState(""),[vialMl,setVialMl]=useState(""),[checks,setChecks]=useState<boolean[]>([]),[labelConfirmed,setLabelConfirmed]=useState(false),[online,setOnline]=useState(true),[installOpen,setInstallOpen]=useState(false);
 useEffect(()=>{setOnline(navigator.onLine);setWeightUnit(localStorage.getItem("preferredWeightUnit")||"kg");const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[]);
 const ageN=Number(age),adult=ageN>=12,elderly=ageN>=65,underOne=age!==""&&ageN<1,kg=weightUnit==="lb"?Number(weight)/2.20462:Number(weight),ageOk=age!==""&&ageN>=0&&ageN<130&&!underOne,weightOk=kg>0&&kg<350;
 const allowedRates=route==="IN"&&!adult?[2]:[1,2],rateOk=doseRate!==null&&allowedRates.includes(doseRate),dose=kg*(doseRate||0),concentration=Number(amount)>0&&Number(vialMl)>0?Number(amount)/Number(vialMl):0,volume=concentration?dose/concentration:0,unusual=concentration>0&&Math.abs(concentration-50)>.01,inVolumeWarning=route==="IN"&&volume>2,repeatMinutes=route==="IN"?10:5,maxCumulativeRate=route==="IN"?4:3,stale=new Date()>REVIEW_DATE;
 const safetyItems=elderly?[...baseSafety,"Strongly considered ½ typical dosing because patient is 65 or older/frail"]:baseSafety;
 useEffect(()=>{setChecks(Array(safetyItems.length).fill(false))},[elderly]);
 useEffect(()=>{setDoseRate(route==="IN"&&!adult?2:null)},[route,adult]);
 const visible:Step[]=["drug","reason","age","weight","safety","vial","review"],position=visible.indexOf(step),progress=((position+1)/visible.length)*100;
 const valid=useMemo(()=>({drug:drug==="fentanyl",reason:reason==="Moderate to severe pain",age:ageOk,weight:weightOk,safety:checks.length===safetyItems.length&&checks.every(Boolean),vial:!!route&&rateOk&&Number(amount)>0&&Number(vialMl)>0&&labelConfirmed&&!inVolumeWarning,review:true}),[drug,reason,ageOk,weightOk,checks,safetyItems.length,route,rateOk,amount,vialMl,labelConfirmed,inVolumeWarning]);
 const next=()=>{if(valid[step])setStep(visible[Math.min(position+1,visible.length-1)])},back=()=>setStep(visible[Math.max(position-1,0)]),setUnit=(u:string)=>{setWeightUnit(u);setWeight("");localStorage.setItem("preferredWeightUnit",u)},reset=()=>{setStep("drug");setDrug("");setSearch("");setReason("");setAge("");setWeight("");setWeightSource("actual");setRoute(null);setDoseRate(null);setAmount("");setVialMl("");setChecks([]);setLabelConfirmed(false)};
 return <main className="wizard-app"><header><div className="brand"><b>M</b><span><strong>Metro Med Dose</strong><small>Guided medication cross-check</small></span></div><div className="header-actions"><span className={`connection ${online?"online":"offline"}`}>{online?"Online":"Offline ready"}</span><button onClick={()=>setInstallOpen(true)}>Install</button></div></header>
 <section className="wizard-shell">{ageOk&&step!=="drug"&&step!=="reason"&&<div className="patient-strip"><b>{elderly?"Geriatric":adult?"Adult":"Pediatric"}</b><span>Age {age}</span>{weightOk&&<span>{fmt(kg)} kg</span>}<small>{sourceLabel(weightSource)}</small></div>}<div className="wizard-top"><button className="back" onClick={back} disabled={step==="drug"}>‹ Back</button><span>Step {position+1} of {visible.length}</span><button className="start-over" onClick={reset}>Start over</button></div><div className="progress"><i style={{width:`${progress}%`}}/></div>
 <div className={`clinical-banner ${stale?"stale":""}`}><b>{stale?"Protocol review overdue":"DMP verified"}</b><span>Denver Metro Protocol • {PROTOCOL_DATE} • Approved July 1, 2026 • Next review January 2027</span></div>
 {step==="drug"&&<Screen eyebrow="START" title="Which medication was requested?" help="Only physician-reviewed medication pathways are selectable."><label className="drug-search"><span>Search generic or brand name</span><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Start typing a medication"/></label><div className="choice-grid">{drugs.filter(d=>(d.name+" "+d.brand).toLowerCase().includes(search.toLowerCase())).map(d=><button key={d.id} disabled={!d.active} className="choice" onClick={()=>{setDrug(d.id);setTimeout(()=>setStep("reason"),120)}}><span className="rx">Rx</span><span><b>{d.name}</b><small>{d.brand} • {d.sub}</small></span>{d.active?<i>›</i>:<em>Pending review</em>}</button>)}</div></Screen>}
 {step==="reason"&&<Screen eyebrow="INDICATION" title="Why is fentanyl being given?" help="DMP 9230 limits this pathway to analgesia. Sedation for pacing or cardioversion is a benzodiazepine pathway."><button className="big-choice" onClick={()=>{setReason("Moderate to severe pain");setTimeout(()=>setStep("age"),120)}}><span>Moderate to severe pain</span><i>›</i></button><div className="source-note">Hemodynamically stable patient with traumatic or medical pain.</div></Screen>}
 {step==="age"&&<Screen eyebrow="PATIENT" title="Enter the patient’s age" help="DMP defines adult as 12 years or older. Fentanyl in patients under 1 year requires Base Contact."><label className="giant-input"><span>Age in years</span><input autoFocus inputMode="decimal" placeholder="0" value={age} onChange={e=>setAge(e.target.value)}/></label>{underOne?<div className="hard-stop"><b>BASE CONTACT REQUIRED</b><span>DMP does not provide standing-order Fentanyl dosing for patients under 1 year.</span></div>:ageOk&&<div className="classification"><span>DMP category</span><b>{elderly?"Geriatric consideration":adult?"Adult":"Pediatric 1–11 years"}</b></div>}<Next enabled={valid.age} onClick={next}/></Screen>}
 {step==="weight"&&<Screen eyebrow="WEIGHT-BASED DOSE" title="Enter the calculation weight" help="DMP recommends a standardized age-, weight- or length-based system for every pediatric patient."><div className="source-grid">{[["actual","Actual"],["estimated","Estimated"],["tape","Length-based tape"]].map(([id,label])=><button key={id} className={weightSource===id?"selected":""} onClick={()=>{setWeightSource(id);if(id==="tape")setUnit("kg")}}>{label}</button>)}</div>{weightSource!=="tape"&&<div className="unit-toggle"><button className={weightUnit==="kg"?"selected":""} onClick={()=>setUnit("kg")}>Kilograms</button><button className={weightUnit==="lb"?"selected":""} onClick={()=>setUnit("lb")}>Pounds</button></div>}<label className="giant-input"><span>{weightSource==="tape"?"Weight printed on tape (kg)":`Patient weight (${weightUnit})`}</span><input autoFocus inputMode="decimal" placeholder="0" value={weight} onChange={e=>setWeight(e.target.value)}/></label>{weightOk&&<div className="classification"><span>Calculation weight</span><b>{fmt(kg)} kg</b></div>}<Next enabled={valid.weight} onClick={next}/></Screen>}
 {step==="safety"&&<Screen eyebrow="CONTRAINDICATIONS" title="Confirm only the applicable checks" help="These checks come from DMP 9230 Opioids. Every statement must be true."><div className="safety-list">{safetyItems.map((x,i)=><label key={x} className={checks[i]?"checked":""}><input type="checkbox" checked={!!checks[i]} onChange={e=>setChecks(checks.map((v,n)=>n===i?e.target.checked:v))}/><span><b>{i+1}</b>{x}</span></label>)}</div><a className="protocol-link" href={PROTOCOL_URL} target="_blank" rel="noreferrer">Open DMP 9230 Opioids ↗</a><Next enabled={valid.safety} onClick={next}/></Screen>}
 {step==="vial"&&<Screen eyebrow="ROUTE, DOSE & VIAL" title="Build the applicable Fentanyl dose" help="Route selection changes the allowed dose, repeat interval and cumulative maximum."><div className="route-label">Route available in DMP 9230</div><div className="route-grid">{(["IV/IO","IM","IN"] as Route[]).map(r=><button className={route===r?"selected":""} onClick={()=>{setRoute(r);setLabelConfirmed(false)}} key={r}>{r}</button>)}</div>{route&&<><div className="route-rule"><b>{route==="IN"?"IN Fentanyl":"IV/IO/IM Fentanyl"}</b><span>Repeat after {repeatMinutes} minutes • Maximum cumulative {maxCumulativeRate} mcg/kg</span>{route==="IN"&&<small>Maximum 1 mL per nostril; IV preferred for repeat dosing.</small>}{route==="IM"&&<small>IM absorption and onset may be erratic; IV is preferred for titration.</small>}</div><div className="route-label">Initial protocol dose</div>{allowedRates.length===1?<div className="locked-dose"><b>2 mcg/kg</b><span>Pediatric IN dose specified by DMP</span></div>:<div className="dose-rate-grid">{allowedRates.map(n=><button className={doseRate===n?"selected":""} onClick={()=>setDoseRate(n)} key={n}><b>{n} mcg/kg</b><span>{n===1?"Lower end":"Upper end"} of DMP range</span></button>)}</div>}</>}
 <div className="med-verify"><div className="photo-placeholder"><div className="drawn-vial"><small>FENTANYL</small><b>VIAL</b><small>PHOTO REQUIRED</small></div><span>Approved department photo pending</span></div><div className="dose-card"><small>DMP 9230</small><h3>Fentanyl • Pain</h3><p><span>Route</span><b>{route||"Select route"}</b></p><p><span>Initial dose</span><b>{doseRate? `${doseRate} mcg/kg`:"Select dose"}</b></p><p><span>Calculated</span><b>{doseRate?`${fmt(dose)} mcg`:"—"}</b></p></div></div>
 <h3 className="label-heading">Enter exactly what the physical vial says</h3><button className="common-vial" onClick={()=>{setAmount("100");setVialMl("2");setLabelConfirmed(false)}}><b>Department review example</b><span>100 mcg in 2 mL</span></button><div className="vial-entry"><label><span>Total drug</span><div><input inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setLabelConfirmed(false)}} placeholder="0"/><b>mcg</b></div></label><label><span>Total volume</span><div><input inputMode="decimal" value={vialMl} onChange={e=>{setVialMl(e.target.value);setLabelConfirmed(false)}} placeholder="0"/><b>mL</b></div></label></div>{concentration>0&&<div className={`concentration-check ${unusual?"caution":""}`}><span>{unusual?"UNUSUAL VS REVIEW EXAMPLE":"Entered concentration"}</span><b>{fmt(concentration)} mcg/mL</b></div>}{inVolumeWarning&&<div className="hard-stop"><b>IN VOLUME EXCEEDS DMP LIMIT</b><span>{fmt(volume)} mL total exceeds 1 mL per nostril. Choose an appropriate route or concentration.</span></div>}<label className={`label-confirm ${labelConfirmed?"checked":""}`}><input type="checkbox" checked={labelConfirmed} onChange={e=>setLabelConfirmed(e.target.checked)}/><span>Medication, units and concentration match the physical container</span></label><Next enabled={valid.vial} onClick={next} text="Review final dose"/></Screen>}
 {step==="review"&&<Screen eyebrow="FINAL CROSS-CHECK" title="Confirm the complete medication plan" help="Read the action line aloud, then verify every input and protocol rule."><div className="action-line"><small>INITIAL DOSE</small><strong>GIVE {fmt(dose)} mcg = DRAW {fmt(volume)} mL</strong><b>{route}</b></div><div className="final-card"><div className="final-drug"><span>Medication</span><b>Fentanyl</b><small>Moderate to severe pain • {route}</small></div><Review label="Patient" value={`${elderly?"Geriatric":adult?"Adult":"Pediatric"} • age ${age} • ${fmt(kg)} kg (${sourceLabel(weightSource)})`}/><Review label="DMP initial dose" value={`${doseRate} mcg/kg = ${fmt(dose)} mcg`}/><Review label="Repeat / cumulative limit" value={`After ${repeatMinutes} min • max ${maxCumulativeRate} mcg/kg cumulative`}/>{route==="IN"&&<Review label="IN volume" value={`${fmt(volume)} mL total • maximum 1 mL per nostril`}/>}<Review label="Vial entered" value={`${amount} mcg in ${vialMl} mL = ${fmt(concentration)} mcg/mL`}/><Review label="Volume calculation" value={`${fmt(dose)} mcg ÷ ${fmt(concentration)} mcg/mL = ${fmt(volume)} mL`}/><Review label="Protocol source" value="DMP 9230 • July 2026"/></div><div className="final-warning"><b>DMP medication cross-check still required</b><span>Verify the Six Rights with a practice partner and verbal repeat-back before administration. Obtain repeat vital signs after intervention.</span></div>{adult&&<div className="source-note">Adult doses may be rounded to the nearest 25 mcg. Initial adult dose is typically 100 mcg. Strongly consider ½ typical dosing in elderly or frail patients.</div>}<button className="new-calc" onClick={reset}>Start a new calculation</button></Screen>}
 </section>{installOpen&&<div className="modal-backdrop" onClick={()=>setInstallOpen(false)}><section className="install-modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setInstallOpen(false)}>×</button><b className="app-icon">M</b><h2>Install for offline use</h2><ol><li>Open in Safari and tap Share.</li><li>Choose <b>Add to Home Screen</b>.</li><li>Open once online after each protocol update.</li></ol><p>Cached protocol version: Denver Metro • {PROTOCOL_DATE}</p></section></div>}</main>
}
function Screen({eyebrow,title,help,children}:{eyebrow:string,title:string,help:string,children:ReactNode}){return <section className="wizard-card"><small className="eyebrow">{eyebrow}</small><h1>{title}</h1><p className="screen-help">{help}</p>{children}</section>}
function Next({enabled,onClick,text="Continue"}:{enabled:boolean,onClick:()=>void,text?:string}){return <button className="continue" disabled={!enabled} onClick={onClick}>{text}<span>→</span></button>}
function Review({label,value}:{label:string,value:string}){return <div className="review-row"><span>{label}</span><b>{value}</b></div>}
function fmt(n:number){return Number.isFinite(n)?Number(n.toFixed(2)).toString():"—"}
function sourceLabel(s:string){return s==="tape"?"Length-based tape":s==="estimated"?"Estimated":"Actual weight"}
