export type GenericDoseUnit="mg"|"mcg"|"g"|"mEq"|"mL"|"drops"|"sprays"|"device"|"treatment";
export type DoseFormula=
  |{kind:"fixed";amount:number;unit:GenericDoseUnit}
  |{kind:"range";min:number;max:number;unit:GenericDoseUnit}
  |{kind:"perKg";amount:number;unit:GenericDoseUnit;min?:number;max?:number}
  |{kind:"ageBands";unit:GenericDoseUnit;bands:{min:number;max:number;amount:number;label:string}[]}
  |{kind:"instruction";unit:GenericDoseUnit;text:string};
export type GenericDosePath={
  id:string;label:string;agent:string;patient:"adult"|"pediatric"|"all";minAge?:number;maxAge?:number;
  route:string;formula:DoseFormula;repeat:string;administration:string;protocol:string;
  baseContact?:string;volumeRequired?:boolean;suggestedConcentration?:number;concentrationUnit?:string;
  monitoring?:string[];special?:string[];requiresWeight?:boolean;
  repeatAfterMinutes?:number;maxAdministrations?:number;maxCumulative?:number;maxCumulativePerKg?:number;absoluteCumulativeMax?:number;openEndedRepeats?:boolean;
};
export type GenericMedication={
  id:string;name:string;protocolId:string;page:number;contraindications:string[];paths:GenericDosePath[];
};
const fixed=(amount:number,unit:GenericDoseUnit):DoseFormula=>({kind:"fixed",amount,unit});
const kg=(amount:number,unit:GenericDoseUnit,min?:number,max?:number):DoseFormula=>({kind:"perKg",amount,unit,min,max});
const instruction=(text:string,unit:GenericDoseUnit="treatment"):DoseFormula=>({kind:"instruction",text,unit});

export const genericMedications:Record<string,GenericMedication>={
  acetaminophen:{id:"acetaminophen",name:"Acetaminophen",protocolId:"9005",page:122,contraindications:["Acetaminophen allergy","Chronic liver disease","Therapeutic acetaminophen within 6 hours or more than 3 g in the last 24 hours"],paths:[
    {id:"adult-po",label:"Adult pain or fever — PO",agent:"Acetaminophen",patient:"adult",route:"PO",formula:fixed(1000,"mg"),repeat:"No repeat dose listed; verify prior 24-hour total.",administration:"Give orally.",protocol:"Pain Management"},
    {id:"adult-iv",label:"Adult moderate/severe pain — IV infusion",agent:"Acetaminophen",patient:"adult",route:"IV infusion",formula:fixed(1000,"mg"),repeat:"No repeat dose listed; verify prior 24-hour total.",administration:"Infuse over 15 minutes.",protocol:"Pain Management",volumeRequired:true},
    {id:"ped-po",label:"Pediatric pain or fever — PO",agent:"Acetaminophen",patient:"pediatric",minAge:.5,maxAge:12,route:"PO",formula:kg(15,"mg"),repeat:"No repeat dose listed; verify prior dosing.",administration:"DMP chart uses 160 mg/5 mL oral solution and rounded age/weight bands.",protocol:"Pain Management",suggestedConcentration:32,concentrationUnit:"mg/mL",special:["Under 6 months requires Base contact."]},
  ]},
  amiodarone:{id:"amiodarone",name:"Amiodarone",protocolId:"9030",page:127,contraindications:["Second- or third-degree AV block","Cardiogenic shock","Do not use for ventricular escape beats or accelerated idioventricular rhythm"],paths:[
    {id:"adult-arrest-1",label:"Adult refractory/recurrent VF/VT — initial",agent:"Amiodarone",patient:"adult",route:"IV/IO bolus",formula:fixed(300,"mg"),repeat:"Additional 150 mg in 3–5 minutes if shock-refractory or recurrent VF/VT.",administration:"IV/IO bolus during pulseless arrest.",protocol:"Medical Pulseless Arrest",volumeRequired:true},
    {id:"adult-arrest-2",label:"Adult refractory/recurrent VF/VT — additional",agent:"Amiodarone",patient:"adult",route:"IV/IO bolus",formula:fixed(150,"mg"),repeat:"This is the listed additional dose.",administration:"IV/IO bolus during pulseless arrest.",protocol:"Medical Pulseless Arrest",volumeRequired:true},
    {id:"adult-wct",label:"Adult symptomatic VT / undifferentiated WCT with pulse",agent:"Amiodarone",patient:"adult",route:"IV infusion",formula:fixed(150,"mg"),repeat:"Further dosing requires physician direction.",administration:"Infuse over 10 minutes.",protocol:"Tachyarrhythmia with Poor Perfusion",baseContact:"Direct Base order required.",volumeRequired:true},
    {id:"ped-arrest",label:"Pediatric refractory VF/VT arrest",agent:"Amiodarone",patient:"pediatric",route:"IV/IO bolus",formula:kg(5,"mg"),repeat:"Contact Base for additional doses.",administration:"IV/IO bolus during pulseless arrest.",protocol:"Medical Pulseless Arrest",volumeRequired:true},
  ]},
  antiemetics:{id:"antiemetics",name:"Antiemetics",protocolId:"9040",page:128,contraindications:["Confirm agent-specific age and contraindications","Promethazine: respiratory/CNS depression, sulfite allergy, or age under 2","Metoclopramide: suspected bowel obstruction or age under 8"],paths:[
    {id:"ond-adult",label:"Ondansetron — adult",agent:"Ondansetron",patient:"adult",route:"IV/IM/PO/ODT",formula:fixed(4,"mg"),repeat:"May repeat once as needed.",administration:"Use selected available route.",protocol:"Abdominal Pain/Vomiting",volumeRequired:true,maxAdministrations:2},
    {id:"ond-ped-4",label:"Ondansetron — pediatric 4 to <12 years",agent:"Ondansetron",patient:"pediatric",minAge:4,maxAge:12,route:"IV/PO/ODT",formula:fixed(4,"mg"),repeat:"No repeat dose listed.",administration:"Use selected available route.",protocol:"Abdominal Pain/Vomiting",volumeRequired:true},
    {id:"ond-ped-6m",label:"Ondansetron — pediatric 6 months to <4 years",agent:"Ondansetron",patient:"pediatric",minAge:.5,maxAge:4,route:"IV/PO/ODT",formula:fixed(2,"mg"),repeat:"No repeat dose listed.",administration:"Under 6 months requires Base contact.",protocol:"Abdominal Pain/Vomiting",volumeRequired:true},
    {id:"prom-adult",label:"Promethazine — adult",agent:"Promethazine",patient:"adult",route:"IV/IM",formula:fixed(12.5,"mg"),repeat:"May repeat once as needed.",administration:"Monitor for hypotension, CNS depression and tissue injury with extravasation.",protocol:"Abdominal Pain/Vomiting",volumeRequired:true,maxAdministrations:2},
    {id:"prom-ped",label:"Promethazine — pediatric 2 to <12 years",agent:"Promethazine",patient:"pediatric",minAge:2,maxAge:12,route:"IV/IM",formula:kg(1,"mg",undefined,12.5),repeat:"No repeat dose listed.",administration:"Maximum single dose 12.5 mg.",protocol:"Abdominal Pain/Vomiting",volumeRequired:true},
    {id:"met-adult",label:"Metoclopramide — adult",agent:"Metoclopramide",patient:"adult",route:"IV/IM",formula:fixed(10,"mg"),repeat:"No repeat dose listed.",administration:"Monitor for dystonia or akathisia.",protocol:"Abdominal Pain/Vomiting",volumeRequired:true},
    {id:"met-ped",label:"Metoclopramide — pediatric 8 to <12 years",agent:"Metoclopramide",patient:"pediatric",minAge:8,maxAge:12,route:"IV/IM",formula:fixed(5,"mg"),repeat:"No repeat dose listed.",administration:"Not indicated below age 8.",protocol:"Abdominal Pain/Vomiting",volumeRequired:true},
    {id:"drop-antiemetic",label:"Droperidol — adult intractable vomiting",agent:"Droperidol",patient:"adult",route:"Slow IV/IM",formula:fixed(1.25,"mg"),repeat:"No repeat dose listed for antiemetic use.",administration:"Cardiac monitoring; slow push when IV.",protocol:"Antiemetics",volumeRequired:true},
  ]},
  antipsychotics:{id:"antipsychotics",name:"Antipsychotics",protocolId:"9045",page:129,contraindications:["Suspected ACS/AMI","SBP under 100 mmHg or no palpable radial pulse","Respiratory depression","Known QTc prolongation","Pregnancy"],paths:[
    {id:"drop-adult",label:"Droperidol — adult IMC-RASS +3/+4",agent:"Droperidol",patient:"adult",route:"Slow IV/IM",formula:fixed(5,"mg"),repeat:"If still +3/+4 after 5 minutes, repeat a butyrophenone dose or switch to benzodiazepine; further medication requires Base.",administration:"Apply ECG, EtCO₂, SpO₂ and establish IV as soon as possible.",protocol:"Agitated/Combative Patient",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"drop-imminent",label:"Droperidol — adult +4 with imminent bodily harm",agent:"Droperidol",patient:"adult",route:"IM",formula:fixed(10,"mg"),repeat:"Additional sedation requires Base.",administration:"IM only for this pathway.",protocol:"Agitated/Combative Patient",volumeRequired:true},
    {id:"drop-ped",label:"Droperidol — pediatric 8 to <12 years",agent:"Droperidol",patient:"pediatric",minAge:8,maxAge:12,route:"IV/IO/IM",formula:kg(.025,"mg",undefined,1.25),repeat:"No standing repeat listed; additional sedation requires Base.",administration:"Maximum single dose 1.25 mg.",protocol:"Agitated/Combative Patient",volumeRequired:true},
    {id:"halo-adult",label:"Haloperidol — adult IMC-RASS +3/+4",agent:"Haloperidol",patient:"adult",route:"Slow IV/IM",formula:fixed(5,"mg"),repeat:"If still +3/+4 after 5 minutes, repeat a butyrophenone dose or switch to benzodiazepine; further medication requires Base.",administration:"Apply ECG, EtCO₂, SpO₂ and establish IV as soon as possible.",protocol:"Agitated/Combative Patient",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"halo-imminent",label:"Haloperidol — adult +4 with imminent bodily harm",agent:"Haloperidol",patient:"adult",route:"IM",formula:fixed(10,"mg"),repeat:"Additional sedation requires Base.",administration:"Use when droperidol is unavailable.",protocol:"Agitated/Combative Patient",volumeRequired:true},
    {id:"halo-ped",label:"Haloperidol — pediatric 8 to <12 years",agent:"Haloperidol",patient:"pediatric",minAge:8,maxAge:12,route:"IM",formula:kg(.05,"mg",undefined,2.5),repeat:"No standing repeat listed; additional sedation requires Base.",administration:"Maximum single dose 2.5 mg.",protocol:"Agitated/Combative Patient",volumeRequired:true},
    {id:"olan-adult",label:"Olanzapine — adult IMC-RASS +3/+4",agent:"Olanzapine",patient:"adult",route:"Slow IV/IM",formula:fixed(5,"mg"),repeat:"If still +3/+4 after 5 minutes, repeat olanzapine or switch to benzodiazepine; further medication requires Base.",administration:"Avoid synergistic oversedation with benzodiazepines.",protocol:"Agitated/Combative Patient",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"olan-imminent",label:"Olanzapine — adult +4 with imminent bodily harm",agent:"Olanzapine",patient:"adult",route:"IM",formula:fixed(10,"mg"),repeat:"Additional sedation requires Base.",administration:"IM only for this pathway.",protocol:"Agitated/Combative Patient",volumeRequired:true},
    {id:"olan-odt",label:"Olanzapine — cooperative adult at high deterioration risk",agent:"Olanzapine",patient:"adult",route:"ODT",formula:fixed(10,"mg"),repeat:"Additional sedation requires Base.",administration:"Patient must be cooperative and able to self-administer.",protocol:"Agitated/Combative Patient"},
    {id:"olan-ped",label:"Olanzapine — pediatric 8 to <12 years",agent:"Olanzapine",patient:"pediatric",minAge:8,maxAge:12,route:"IM or ODT",formula:{kind:"ageBands",unit:"mg",bands:[{min:8,max:10,amount:2.5,label:"8–9 years"},{min:10,max:12,amount:5,label:"10–11 years"}]},repeat:"Additional sedation requires Base.",administration:"For autism or severe developmental delay, ODT is preferred.",protocol:"Agitated/Combative Patient",volumeRequired:true},
  ]},
  aspirin:{id:"aspirin",name:"Aspirin",protocolId:"9050",page:134,contraindications:["Active gastrointestinal bleeding","Aspirin allergy","Age under 16 years"],paths:[{id:"acs",label:"Suspected acute coronary syndrome",agent:"Aspirin",patient:"adult",minAge:16,route:"PO — chew",formula:fixed(324,"mg"),repeat:"Single prehospital dose.",administration:"Four 81 mg chewable tablets.",protocol:"Chest Pain"}]},
  atropine:{id:"atropine",name:"Atropine",protocolId:"9060",page:135,contraindications:["Do not use for stable bradycardia without medical-control direction","Closed-angle glaucoma precaution"],paths:[
    {id:"brady-adult",label:"Adult unstable bradycardia",agent:"Atropine",patient:"adult",route:"IV/IO bolus",formula:fixed(1,"mg"),repeat:"Repeat every 3–5 minutes to maximum 3 mg; stop at adequate mentation and blood pressure.",administration:"IV/IO bolus.",protocol:"Bradyarrhythmia with Poor Perfusion",volumeRequired:true,repeatAfterMinutes:3,maxAdministrations:3,maxCumulative:3},
    {id:"brady-ped",label:"Pediatric unstable bradycardia",agent:"Atropine",patient:"pediatric",route:"IV/IO bolus",formula:kg(.02,"mg",.1,.5),repeat:"Further dosing per applicable protocol/Base direction.",administration:"Minimum 0.1 mg; maximum single dose 0.5 mg.",protocol:"Bradyarrhythmia with Poor Perfusion",volumeRequired:true},
    {id:"poison-adult",label:"Adult ≥40 kg organophosphate poisoning",agent:"Atropine",patient:"adult",route:"IV/IM",formula:fixed(2,"mg"),repeat:"Contact Base for additional doses.",administration:"For moderate/severe toxicity.",protocol:"Poisoning/Overdose",volumeRequired:true,requiresWeight:true},
    {id:"poison-ped",label:"Patient <40 kg organophosphate poisoning",agent:"Atropine",patient:"pediatric",route:"IV/IM",formula:kg(.02,"mg",.1),repeat:"Contact Base for additional doses.",administration:"For moderate/severe toxicity; minimum 0.1 mg.",protocol:"Poisoning/Overdose",volumeRequired:true},
  ]},
  diazepam:{id:"diazepam",name:"Diazepam",protocolId:"9070",page:136,contraindications:["Hypotension","Respiratory depression","Opioid coadministration requires a direct physician verbal order"],paths:[
    {id:"adult-seizure",label:"Adult seizure",agent:"Diazepam",patient:"adult",route:"IV/IO/IM",formula:fixed(5,"mg"),repeat:"May repeat once after 5 minutes if still seizing; more than 2 doses requires Base.",administration:"IM absorption is poor/delayed and is not recommended for status epilepticus; Midazolam is preferred for IM.",protocol:"Seizure",volumeRequired:true,requiresWeight:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"adult-sedation",label:"Adult sedation for cardioversion or TCP",agent:"Diazepam",patient:"adult",route:"IV/IO/IM",formula:fixed(5,"mg"),repeat:"May repeat once after 5 minutes; more than 2 doses requires Base.",administration:"Continuously monitor cardiac rhythm, SpO₂ and ventilation.",protocol:"Cardioversion / Transcutaneous Pacing",volumeRequired:true,requiresWeight:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"adult-agitation",label:"Adult agitation IMC-RASS +3/+4",agent:"Diazepam",patient:"adult",route:"IV/IO/IM",formula:fixed(5,"mg"),repeat:"If still +3/+4 after 5 minutes, switch to antipsychotic; further sedation requires Base.",administration:"Continuously monitor cardiac rhythm, SpO₂ and ventilation.",protocol:"Agitated/Combative Patient",volumeRequired:true,requiresWeight:true},
    {id:"ped-young",label:"Pediatric seizure/sedation — >newborn to <5 years",agent:"Diazepam",patient:"pediatric",minAge:.003,maxAge:5,route:"IV/IO/IM",formula:fixed(.5,"mg"),repeat:"May repeat once after 5 minutes if still seizing; more than 2 doses requires Base.",administration:"Not indicated for neonates. IM is not recommended for status epilepticus.",protocol:"Seizure / Cardioversion / TCP",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"ped-older",label:"Pediatric seizure/sedation — age 5 to <12 years",agent:"Diazepam",patient:"pediatric",minAge:5,maxAge:12,route:"IV/IO/IM",formula:fixed(1,"mg"),repeat:"May repeat once after 5 minutes if still seizing; more than 2 doses requires Base.",administration:"IM is not recommended for status epilepticus.",protocol:"Seizure / Cardioversion / TCP",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
  ]},
  lorazepam:{id:"lorazepam",name:"Lorazepam",protocolId:"9070",page:136,contraindications:["Hypotension","Respiratory depression","Opioid coadministration requires a direct physician verbal order"],paths:[
    {id:"adult-seizure",label:"Adult seizure",agent:"Lorazepam",patient:"adult",route:"IV/IO/IM",formula:fixed(4,"mg"),repeat:"May repeat once after 5 minutes if still seizing; more than 2 doses requires Base.",administration:"IM absorption is poor/delayed and is not recommended for status epilepticus.",protocol:"Seizure",volumeRequired:true,requiresWeight:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"ped-seizure",label:"Pediatric seizure",agent:"Lorazepam",patient:"pediatric",route:"IV/IO/IM",formula:kg(.1,"mg",undefined,4),repeat:"May repeat once after 5 minutes if still seizing; more than 2 doses requires Base.",administration:"Maximum single dose 4 mg. IM is not recommended for status epilepticus.",protocol:"Seizure",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"adult-sedation",label:"Adult sedation for cardioversion or TCP",agent:"Lorazepam",patient:"adult",route:"IV/IO/IM",formula:fixed(1,"mg"),repeat:"May repeat once after 5 minutes; more than 2 doses requires Base.",administration:"Continuously monitor cardiac rhythm, SpO₂ and ventilation.",protocol:"Cardioversion / Transcutaneous Pacing",volumeRequired:true,requiresWeight:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"adult-agitation",label:"Adult agitation IMC-RASS +3/+4",agent:"Lorazepam",patient:"adult",route:"IV/IO/IM",formula:fixed(2,"mg"),repeat:"If still +3/+4 after 5 minutes, switch to antipsychotic; further sedation requires Base.",administration:"Continuously monitor cardiac rhythm, SpO₂ and ventilation.",protocol:"Agitated/Combative Patient",volumeRequired:true,requiresWeight:true},
    {id:"ped-agitation",label:"Pediatric agitation — age 8 to <12 years",agent:"Lorazepam",patient:"pediatric",minAge:8,maxAge:12,route:"IV/IO/IM",formula:kg(.05,"mg",undefined,2),repeat:"Further sedation requires Base.",administration:"Maximum single dose 2 mg. Under age 8 requires Base.",protocol:"Agitated/Combative Patient",volumeRequired:true},
  ]},
  calcium:{id:"calcium",name:"Calcium",protocolId:"9080",page:140,contraindications:["Known or suspected hypercalcemia","Known or suspected digoxin toxicity","Flush at least 10 mL between calcium and sodium bicarbonate in the same line"],paths:[
    {id:"gluconate-hyperk",label:"Calcium gluconate — adult hyperkalemia/crush/renal failure",agent:"Calcium gluconate 10%",patient:"adult",route:"IV/IO",formula:fixed(3000,"mg"),repeat:"No routine repeat listed.",administration:"30 mL over 5 minutes; slow push in pulseless arrest.",protocol:"Hyperkalemia / Medical Pulseless Arrest",suggestedConcentration:100,concentrationUnit:"mg/mL",volumeRequired:true},
    {id:"gluconate-ccb-adult",label:"Calcium gluconate — adult CCB overdose",agent:"Calcium gluconate 10%",patient:"adult",route:"IV/IO",formula:fixed(3000,"mg"),repeat:"May repeat every 5 minutes for total of 3 doses under Base order.",administration:"Infuse over 5 minutes.",protocol:"Poisoning/Overdose",baseContact:"Direct Base order required.",suggestedConcentration:100,concentrationUnit:"mg/mL",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:3},
    {id:"gluconate-ccb-ped",label:"Calcium gluconate — pediatric CCB overdose",agent:"Calcium gluconate 10%",patient:"pediatric",route:"IV/IO",formula:kg(60,"mg",undefined,1000),repeat:"May repeat every 5 minutes for total of 3 doses under Base order.",administration:"0.6 mL/kg, maximum 1 g, over 5 minutes.",protocol:"Poisoning/Overdose",baseContact:"Direct Base order required.",suggestedConcentration:100,concentrationUnit:"mg/mL",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:3},
    {id:"chloride-hyperk",label:"Calcium chloride — adult hyperkalemia/crush/renal failure",agent:"Calcium chloride 10%",patient:"adult",route:"IV/IO",formula:fixed(1000,"mg"),repeat:"No routine repeat listed.",administration:"10 mL over 5 minutes; slow push in pulseless arrest.",protocol:"Hyperkalemia / Medical Pulseless Arrest",suggestedConcentration:100,concentrationUnit:"mg/mL",volumeRequired:true},
    {id:"chloride-ccb-adult",label:"Calcium chloride — adult CCB overdose",agent:"Calcium chloride 10%",patient:"adult",route:"IV/IO",formula:fixed(1000,"mg"),repeat:"May repeat every 5 minutes for total of 3 doses under Base order.",administration:"Infuse over 5 minutes.",protocol:"Poisoning/Overdose",baseContact:"Direct Base order required.",suggestedConcentration:100,concentrationUnit:"mg/mL",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:3},
    {id:"chloride-ccb-ped",label:"Calcium chloride — pediatric CCB overdose",agent:"Calcium chloride 10%",patient:"pediatric",route:"IV/IO",formula:kg(20,"mg",undefined,1000),repeat:"May repeat every 5 minutes for total of 3 doses under Base order.",administration:"0.2 mL/kg, maximum 1 g, over 5 minutes.",protocol:"Poisoning/Overdose",baseContact:"Direct Base order required.",suggestedConcentration:100,concentrationUnit:"mg/mL",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:3},
  ]},
  dextrose:{id:"dextrose",name:"Dextrose",protocolId:"9090",page:142,contraindications:["Confirm hypoglycemia when possible","Use a patent large vein; extravasation may cause tissue necrosis"],paths:[
    {id:"adult-d10",label:"Adult hypoglycemia — D10 infusion",agent:"Dextrose 10%",patient:"adult",route:"IV/IO infusion",formula:fixed(25,"g"),repeat:"Reassess glucose and clinical response.",administration:"250 mL D10 infusion.",protocol:"Hypoglycemia",suggestedConcentration:.1,concentrationUnit:"g/mL",volumeRequired:true},
    {id:"adult-d50",label:"Adult hypoglycemia — D50 bolus",agent:"Dextrose 50%",patient:"adult",route:"IV/IO bolus",formula:fixed(25,"g"),repeat:"Reassess glucose and clinical response.",administration:"50 mL D50 bolus.",protocol:"Hypoglycemia",suggestedConcentration:.5,concentrationUnit:"g/mL",volumeRequired:true},
    {id:"ped-d10",label:"Pediatric >newborn and <50 kg — D10",agent:"Dextrose 10%",patient:"pediatric",route:"IV/IO infusion",formula:kg(.5,"g",undefined,25),repeat:"Reassess glucose and clinical response.",administration:"5 mL/kg D10; maximum 250 mL.",protocol:"Hypoglycemia",suggestedConcentration:.1,concentrationUnit:"g/mL",volumeRequired:true},
    {id:"newborn-d10",label:"Newborn neurologically altered/unable to feed — D10",agent:"Dextrose 10%",patient:"pediatric",maxAge:.003,route:"IV/IO",formula:fixed(.5,"g"),repeat:"Recheck after 15 minutes.",administration:"Give 5 mL D10.",protocol:"Neonatal Resuscitation",suggestedConcentration:.1,concentrationUnit:"g/mL",volumeRequired:true},
  ]},
  diltiazem:{id:"diltiazem",name:"Diltiazem",protocolId:"9095",page:143,contraindications:["Hypotension","Acute decompensated/symptomatic CHF","AMI","Second- or third-degree AV block","IV beta blocker within 3 hours","Wide-complex tachycardia","Sick sinus without functioning pacemaker","AF/flutter with WPW/short PR","Concern for sepsis"],paths:[
    {id:"initial",label:"Adult AF/flutter RVR or narrow tachycardia refractory to adenosine — initial",agent:"Diltiazem",patient:"adult",route:"IV/IO",formula:kg(.25,"mg"),repeat:"If necessary, repeat in 10 minutes using the second-dose pathway.",administration:"Administer over at least 2–3 minutes. For age >65 use half dose, maximum 10 mg.",protocol:"Tachyarrhythmia with Poor Perfusion",baseContact:"Direct Base order required.",volumeRequired:true,special:["Select the medication-specific over-65 adjustment in the calculator."]},
    {id:"repeat",label:"Adult AF/flutter RVR — second dose after 10 minutes",agent:"Diltiazem",patient:"adult",route:"IV/IO",formula:kg(.35,"mg"),repeat:"This is the listed second dose.",administration:"Administer over at least 2–3 minutes. For age >65 use half dose, maximum 20 mg.",protocol:"Tachyarrhythmia with Poor Perfusion",baseContact:"Direct Base order required.",volumeRequired:true,special:["Select the medication-specific over-65 adjustment in the calculator."]},
  ]},
  dopamine:{id:"dopamine",name:"Dopamine",protocolId:"9110",page:145,contraindications:["Age under 12 years","Do not use for anaphylaxis or status asthmaticus","Agency medical director must authorize this optional medication"],paths:[
    {id:"infusion-5",label:"Dopamine infusion — 5 mcg/kg/min",agent:"Dopamine",patient:"adult",route:"IV/IO infusion",formula:kg(5,"mcg"),repeat:"Reassess after 5 minutes; titrate in 5 mcg/kg/min steps to maximum 20 mcg/kg/min.",administration:"IV DRIP — not IV push. Mix 400 mg/250 mL or 800 mg/500 mL = 1600 mcg/mL.",protocol:"Shock / Bradyarrhythmia / Post-ROSC",suggestedConcentration:1600,concentrationUnit:"mcg/mL",volumeRequired:true},
    {id:"infusion-10",label:"Dopamine infusion — 10 mcg/kg/min",agent:"Dopamine",patient:"adult",route:"IV/IO infusion",formula:kg(10,"mcg"),repeat:"Reassess after 5 minutes; titrate in 5 mcg/kg/min steps to maximum 20 mcg/kg/min.",administration:"IV DRIP — not IV push. Mix 400 mg/250 mL or 800 mg/500 mL = 1600 mcg/mL.",protocol:"Shock / Bradyarrhythmia / Post-ROSC",suggestedConcentration:1600,concentrationUnit:"mcg/mL",volumeRequired:true},
    {id:"infusion-15",label:"Dopamine infusion — 15 mcg/kg/min",agent:"Dopamine",patient:"adult",route:"IV/IO infusion",formula:kg(15,"mcg"),repeat:"Reassess after 5 minutes; titrate in 5 mcg/kg/min steps to maximum 20 mcg/kg/min.",administration:"IV DRIP — not IV push. Mix 400 mg/250 mL or 800 mg/500 mL = 1600 mcg/mL.",protocol:"Shock / Bradyarrhythmia / Post-ROSC",suggestedConcentration:1600,concentrationUnit:"mcg/mL",volumeRequired:true},
    {id:"infusion-20",label:"Dopamine infusion — 20 mcg/kg/min (maximum)",agent:"Dopamine",patient:"adult",route:"IV/IO infusion",formula:kg(20,"mcg"),repeat:"Maximum DMP infusion rate; contact Base if the patient remains unstable.",administration:"IV DRIP — not IV push. Mix 400 mg/250 mL or 800 mg/500 mL = 1600 mcg/mL.",protocol:"Shock / Bradyarrhythmia / Post-ROSC",suggestedConcentration:1600,concentrationUnit:"mcg/mL",volumeRequired:true},
  ]},
  duodote:{id:"duodote",name:"DuoDote",protocolId:"9115",page:146,contraindications:["Use only for suspected nerve-agent exposure with compatible signs and symptoms"],paths:[
    {id:"injector",label:"Suspected nerve-agent poisoning",agent:"DuoDote auto-injector",patient:"all",route:"IM auto-injector",formula:fixed(1,"device"),repeat:"No more than 3 sets of antidotes; endpoint is clear, dry lung sounds.",administration:"Each injector contains atropine 2.1 mg plus pralidoxime 600 mg. Inject mid-outer thigh.",protocol:"Poisoning/Overdose",maxAdministrations:3},
  ]},
  glucagon:{id:"glucagon",name:"Glucagon",protocolId:"9130",page:151,contraindications:["Reconstitute per supplied product","Expect nausea/vomiting; protect airway"],paths:[
    {id:"adult-hypo",label:"Adult hypoglycemia without IV access",agent:"Glucagon",patient:"adult",route:"IM",formula:fixed(1,"mg"),repeat:"Reassess glucose and clinical response.",administration:"IM.",protocol:"Hypoglycemia",volumeRequired:true},
    {id:"ped-hypo-small",label:"Pediatric hypoglycemia — under 25 kg",agent:"Glucagon",patient:"pediatric",route:"IM",formula:fixed(.5,"mg"),repeat:"Reassess glucose and clinical response.",administration:"Use only for patient under 25 kg.",protocol:"Hypoglycemia",volumeRequired:true,requiresWeight:true},
    {id:"ped-hypo-large",label:"Pediatric hypoglycemia — 25 kg or greater",agent:"Glucagon",patient:"pediatric",route:"IM",formula:fixed(1,"mg"),repeat:"Reassess glucose and clinical response.",administration:"Use only for patient 25 kg or greater.",protocol:"Hypoglycemia",volumeRequired:true,requiresWeight:true},
    {id:"adult-overdose",label:"Adult beta-blocker/CCB overdose with hypotension and bradycardia",agent:"Glucagon",patient:"adult",route:"IV bolus",formula:fixed(2,"mg"),repeat:"No repeat dose listed.",administration:"IV bolus.",protocol:"Poisoning/Overdose",volumeRequired:true},
    {id:"ped-overdose",label:"Pediatric beta-blocker/CCB overdose",agent:"Glucagon",patient:"pediatric",route:"IV",formula:kg(.1,"mg"),repeat:"No repeat dose listed.",administration:"For hypotension-for-age, poor perfusion and bradycardia.",protocol:"Poisoning/Overdose",volumeRequired:true},
  ]},
  "hemostatic-agents":{id:"hemostatic-agents",name:"Hemostatic Agents",protocolId:"9150",page:152,contraindications:["Internal, intra-abdominal, intrathoracic or vaginal bleeding","Minor bleeding controlled by direct pressure","Do not use loose granular or powdered agents"],paths:[
    {id:"packing",label:"Uncontrolled external bleeding requiring wound packing",agent:"Agency-approved hemostatic gauze",patient:"all",route:"Topical wound packing",formula:instruction("Pack the wound with one complete agency-approved hemostatic gauze and maintain direct pressure for 3–5 minutes."),repeat:"Apply additional standard gauze/pressure per manufacturer and hemorrhage-control procedure.",administration:"Apply indicated tourniquet first. Follow the specific manufacturer instructions.",protocol:"General Trauma Care"},
  ]},
  hydroxocobalamin:{id:"hydroxocobalamin",name:"Hydroxocobalamin",protocolId:"9160",page:153,contraindications:["Initiate BLS/supportive measures first","Use a dedicated line when possible; compatibility with other drugs is unknown"],paths:[
    {id:"adult",label:"Adult suspected cyanide poisoning with arrest/coma/shock",agent:"Hydroxocobalamin",patient:"adult",route:"IV/IO infusion",formula:fixed(5000,"mg"),repeat:"No repeat dose listed in DMP 9160.",administration:"Reconstitute 5 g with 200 mL NS; rock/invert for at least 60 seconds; infuse over 15 minutes.",protocol:"Carbon Monoxide Exposure / Burns",suggestedConcentration:25,concentrationUnit:"mg/mL",volumeRequired:true},
    {id:"ped",label:"Pediatric suspected cyanide poisoning with arrest/coma/shock",agent:"Hydroxocobalamin",patient:"pediatric",route:"IV/IO infusion",formula:kg(70,"mg",undefined,5000),repeat:"No repeat dose listed in DMP 9160.",administration:"Reconstitute to 25 mg/mL; infuse calculated volume over 15 minutes.",protocol:"Carbon Monoxide Exposure / Burns",suggestedConcentration:25,concentrationUnit:"mg/mL",volumeRequired:true},
  ]},
  ipratropium:{id:"ipratropium",name:"Ipratropium",protocolId:"9170",page:155,contraindications:["MDI formulation: soy or peanut allergy; this does not apply to nebulized solution"],paths:[
    {id:"adult",label:"Adult bronchospasm",agent:"Ipratropium",patient:"adult",route:"Nebulized",formula:fixed(.5,"mg"),repeat:"May repeat twice with albuterol for total of 3 doses.",administration:"Add to albuterol nebulizer.",protocol:"Adult Wheezing",suggestedConcentration:.2,concentrationUnit:"mg/mL",volumeRequired:true,maxAdministrations:3},
    {id:"ped-2",label:"Pediatric age 2 to <12 bronchospasm",agent:"Ipratropium",patient:"pediatric",minAge:2,maxAge:12,route:"Nebulized",formula:fixed(.5,"mg"),repeat:"May repeat twice with albuterol for total of 3 doses.",administration:"Add to albuterol nebulizer.",protocol:"Pediatric Wheezing",suggestedConcentration:.2,concentrationUnit:"mg/mL",volumeRequired:true,maxAdministrations:3},
    {id:"ped-1",label:"Pediatric age 1 to <2 bronchospasm",agent:"Ipratropium",patient:"pediatric",minAge:1,maxAge:2,route:"Nebulized",formula:fixed(.25,"mg"),repeat:"No repetitive dose or continuous nebulizer use.",administration:"Add to albuterol nebulizer.",protocol:"Pediatric Wheezing",suggestedConcentration:.2,concentrationUnit:"mg/mL",volumeRequired:true},
  ]},
  lidocaine:{id:"lidocaine",name:"Lidocaine 2%",protocolId:"9180",page:156,contraindications:["Use caution in elderly patients, liver disease, shock or CHF with poor liver perfusion"],paths:[
    {id:"io",label:"Adult analgesia before IO infusion",agent:"Lidocaine",patient:"adult",route:"Slow IO push",formula:fixed(50,"mg"),repeat:"No repeat dose listed.",administration:"Push slowly over 2–3 minutes.",protocol:"Intraosseous Procedure",suggestedConcentration:20,concentrationUnit:"mg/mL",volumeRequired:true},
    {id:"jelly",label:"Nasotracheal-intubation lubricant",agent:"Lidocaine jelly 2%",patient:"adult",route:"Topical",formula:instruction("Apply a moderate amount to the endotracheal tube shortly before use."),repeat:"Reapply if dried before insertion.",administration:"Do not introduce jelly into the tube lumen.",protocol:"Nasotracheal Intubation"},
  ]},
  naloxone:{id:"naloxone",name:"Naloxone",protocolId:"9210",page:159,contraindications:["Not intended without respiratory depression or impaired airway reflexes","Titrate to adequate ventilation rather than full arousal when possible"],paths:[
    {id:"titrate",label:"Adult or pediatric respiratory/CNS depression — titrated dose",agent:"Naloxone",patient:"all",route:"IV/IO/IM/IN",formula:fixed(.5,"mg"),repeat:"Titrate to desired effect up to 2 mg total.",administration:"Monitor for recurrent depression, withdrawal, vomiting and pulmonary edema.",protocol:"Altered Mental Status / Poisoning",volumeRequired:true,maxAdministrations:4,maxCumulative:2},
    {id:"severe",label:"Adult or pediatric severe respiratory compromise/arrest",agent:"Naloxone",patient:"all",route:"IV/IO/IM/IN",formula:fixed(2,"mg"),repeat:"Higher doses may rarely be used for strongly suspected opioid overdose with insufficient response; titrate to effect.",administration:"A 2 mg bolus is appropriate for severe compromise/arrest.",protocol:"Altered Mental Status / Poisoning",volumeRequired:true},
  ]},
  morphine:{id:"morphine",name:"Morphine",protocolId:"9230",page:163,contraindications:["Hypotension, hemodynamic instability or shock","Respiratory depression","Benzodiazepine coadministration requires a direct physician verbal order","Age under 1 year requires Base"],paths:[
    {id:"adult",label:"Adult moderate-to-severe pain",agent:"Morphine",patient:"adult",route:"IV/IO/IM",formula:{kind:"range",min:5,max:10,unit:"mg"},repeat:"May repeat after 10 minutes to maximum cumulative 10 mg; more requires Base.",administration:"IV is preferred for accurate titration. Morphine may not be given IN.",protocol:"Pain Management",volumeRequired:true,repeatAfterMinutes:10,maxAdministrations:2,maxCumulative:10},
    {id:"ped",label:"Pediatric age 1 to <12 moderate-to-severe pain",agent:"Morphine",patient:"pediatric",minAge:1,maxAge:12,route:"IV/IO/IM",formula:kg(.1,"mg",undefined,6),repeat:"May repeat after 10 minutes to maximum cumulative 0.2 mg/kg or 10 mg; more requires Base.",administration:"Maximum single dose 6 mg. IV is preferred. Morphine may not be given IN.",protocol:"Pain Management",volumeRequired:true,repeatAfterMinutes:10,maxAdministrations:2,maxCumulativePerKg:.2,absoluteCumulativeMax:10},
  ]},
  hydromorphone:{id:"hydromorphone",name:"Hydromorphone",protocolId:"9230",page:163,contraindications:["Hypotension, hemodynamic instability or shock","Respiratory depression","Benzodiazepine coadministration requires a direct physician verbal order","Not indicated for pediatric patients"],paths:[
    {id:"adult",label:"Adult moderate-to-severe pain",agent:"Hydromorphone",patient:"adult",route:"IV/IO/IM",formula:fixed(.5,"mg"),repeat:"May repeat after 10 minutes to maximum cumulative 1.5 mg; more requires Base.",administration:"IV is preferred for accurate titration.",protocol:"Pain Management",volumeRequired:true,repeatAfterMinutes:10,maxAdministrations:3,maxCumulative:1.5},
  ]},
  nitroglycerin:{id:"nitroglycerin",name:"Nitroglycerin",protocolId:"9220",page:161,contraindications:["Suspected right-ventricular STEMI","SBP below 100 mmHg","Recent PDE-5/erectile-dysfunction medication use"],paths:[
    {id:"chest",label:"Adult suspected ACS chest pain",agent:"Nitroglycerin",patient:"adult",route:"Sublingual",formula:fixed(.4,"mg"),repeat:"Every 5 minutes as needed, maximum 3 doses for persistent chest pain.",administration:"Reassess blood pressure and symptoms before every dose.",protocol:"Chest Pain",repeatAfterMinutes:5,maxAdministrations:3},
    {id:"edema",label:"Adult CHF/pulmonary edema",agent:"Nitroglycerin",patient:"adult",route:"Sublingual",formula:fixed(.4,"mg"),repeat:"Every 5 minutes as needed, titrated to symptoms and blood pressure.",administration:"Reassess blood pressure and respiratory status before every dose.",protocol:"CHF/Pulmonary Edema",repeatAfterMinutes:5,openEndedRepeats:true},
  ]},
  nsaids:{id:"nsaids",name:"NSAIDs",protocolId:"9225",page:162,contraindications:["NSAID/aspirin/naproxen allergy","Pregnancy or breastfeeding","GI bleeding or active ulcer","Chronic kidney disease or kidney transplant","Anticoagulant/antiplatelet use or clotting disorder","Multisystem trauma","Acute head trauma or suspected intracranial bleed","Severe dehydration"],paths:[
    {id:"ibu-adult",label:"Ibuprofen — adult pain or fever",agent:"Ibuprofen",patient:"adult",route:"PO",formula:fixed(600,"mg"),repeat:"No repeat dose listed.",administration:"Oral administration.",protocol:"Pain Management"},
    {id:"ibu-ped",label:"Ibuprofen — pediatric 6 months to <12 years",agent:"Ibuprofen",patient:"pediatric",minAge:.5,maxAge:12,route:"PO",formula:kg(10,"mg"),repeat:"No repeat dose listed.",administration:"DMP chart uses 100 mg/5 mL solution with rounded age/weight bands.",protocol:"Pain Management",suggestedConcentration:20,concentrationUnit:"mg/mL",special:["Under 6 months requires Base contact."]},
    {id:"ket-adult",label:"Ketorolac — adult age 12 to 65",agent:"Ketorolac",patient:"adult",maxAge:65.0001,route:"IV/IM",formula:fixed(15,"mg"),repeat:"No repeat dose listed.",administration:"Contraindicated over age 65.",protocol:"Pain Management",volumeRequired:true},
    {id:"ket-ped",label:"Ketorolac — pediatric age 8 to <12",agent:"Ketorolac",patient:"pediatric",minAge:8,maxAge:12,route:"IV/IM",formula:fixed(10,"mg"),repeat:"No repeat dose listed.",administration:"Not indicated below age 8.",protocol:"Pain Management",volumeRequired:true},
  ]},
  "oral-glucose":{id:"oral-glucose",name:"Oral Glucose",protocolId:"9240",page:165,contraindications:["Unable to swallow or protect the airway","Unable to take oral medication"],paths:[
    {id:"tube",label:"Known or suspected hypoglycemia — all ages",agent:"Oral glucose",patient:"all",route:"Buccal",formula:fixed(15,"g"),repeat:"Reassess glucose and clinical response.",administration:"Administer one full 15 g tube buccally.",protocol:"Hypoglycemia / Altered Mental Status"},
  ]},
  oxygen:{id:"oxygen",name:"Oxygen",protocolId:"9250",page:166,contraindications:["Inadequate breathing requires assisted ventilation—not oxygen alone","Avoid unnecessary hyperoxia"],paths:[
    {id:"titrate",label:"Hypoxemia, respiratory distress, shock or other protocol indication",agent:"Oxygen",patient:"all",route:"Appropriate delivery device",formula:instruction("Titrate oxygen to SpO₂ 90–96% when oxygen therapy is indicated."),repeat:"Continuously reassess oxygenation and ventilation.",administration:"Choose the delivery method and flow needed to achieve target; assess ventilation clinically and with waveform capnography.",protocol:"DMP 9250 Oxygen"},
  ]},
  phenylephrine:{id:"phenylephrine",name:"Phenylephrine (intranasal)",protocolId:"9260",page:167,contraindications:["Avoid administration into the eyes"],paths:[
    {id:"drops",label:"Before nasotracheal intubation — drops",agent:"Phenylephrine 1%",patient:"all",route:"Intranasal",formula:fixed(2,"drops"),repeat:"No repeat dose listed.",administration:"Instill in the selected nostril before nasotracheal intubation.",protocol:"Nasotracheal Intubation"},
    {id:"sprays-nti",label:"Before nasotracheal intubation — spray",agent:"Phenylephrine",patient:"all",route:"Intranasal",formula:fixed(2,"sprays"),repeat:"No repeat dose listed.",administration:"Administer in the selected nostril before nasotracheal intubation.",protocol:"Nasotracheal Intubation"},
    {id:"sprays-epi",label:"Active epistaxis",agent:"Phenylephrine",patient:"all",route:"Intranasal",formula:fixed(2,"sprays"),repeat:"No repeat dose listed.",administration:"Have patient blow out clots first, then spray affected naris or nares.",protocol:"Epistaxis"},
  ]},
  "racemic-epinephrine":{id:"racemic-epinephrine",name:"Racemic Epinephrine",protocolId:"9270",page:168,contraindications:["Confirm medication is racemic epinephrine 2.25% for inhalation","Do not confuse medication effects with worsening respiratory failure"],paths:[
    {id:"stridor",label:"Stridor at rest — all ages",agent:"Racemic epinephrine 2.25%",patient:"all",route:"Nebulized",formula:fixed(.5,"mL"),repeat:"No repeat dose listed.",administration:"Mix 0.5 mL medication in 3 mL saline; nebulize at 6–8 L/min over 15 minutes.",protocol:"Pediatric Stridor/Croup"},
  ]},
  "sodium-bicarbonate":{id:"sodium-bicarbonate",name:"Sodium Bicarbonate",protocolId:"9280",page:169,contraindications:["Metabolic or respiratory alkalosis","Hypocalcemia","Hypokalemia","Flush at least 10 mL between calcium and sodium bicarbonate in the same line"],paths:[
    {id:"hyperk",label:"Hyperkalemia / crush / renal failure / hyperkalemic arrest",agent:"Sodium bicarbonate 8.4%",patient:"all",route:"Slow IV/IO push",formula:kg(1,"mEq"),repeat:"May repeat twice every 5 minutes if needed.",administration:"Slow IV/IO push.",protocol:"Hyperkalemia / Medical Pulseless Arrest",suggestedConcentration:1,concentrationUnit:"mEq/mL",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:3},
    {id:"sodium-channel",label:"Sodium-channel blocker poisoning with QRS >120 ms or ventricular arrhythmia",agent:"Sodium bicarbonate 8.4%",patient:"all",route:"Slow IV/IO push",formula:kg(1,"mEq"),repeat:"May repeat twice every 5 minutes or until QRS narrows.",administration:"Slow IV/IO push.",protocol:"Poisoning/Overdose",suggestedConcentration:1,concentrationUnit:"mEq/mL",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:3},
  ]},
  "ophthalmic-anesthetics":{id:"ophthalmic-anesthetics",name:"Topical Ophthalmic Anesthetics",protocolId:"9290",page:170,contraindications:["Local-anesthetic allergy","Globe laceration or rupture","Do not give to patient for self-administration"],paths:[
    {id:"eye",label:"Eye pain/corneal abrasion or to facilitate irrigation",agent:"Proparacaine or tetracaine",patient:"all",route:"Affected eye",formula:fixed(2,"drops"),repeat:"Contact Base for repeat dosing.",administration:"Do not administer until transport has begun and the patient has consented to transport. Single-patient use; discard remainder.",protocol:"DMP 9290"},
  ]},
};

export function genericMedication(id:string){return genericMedications[id]}
