import {useEffect,useMemo,useState} from "react";
import type {GenericMedication,GenericDosePath} from "./dmpMedicationData";
import "./genericMedication.css";

type RecordedAdministration={drug:string;reason:string;route:string;dose:number;unit:string;volume:number;time:number;concentration:string;patient?:string;baseAuthorization?:{physician:string;time:number;reason:string}};
type LocalAdministration={dose:number;volume:number;time:number};
type Props={medication:GenericMedication;close:()=>void;record:(entry:RecordedAdministration)=>void;openProtocol:()=>void};
type AgeUnit="years"|"months"|"days";
type Step="medication"|"patient"|"weight"|"safety"|"result";

export default function DmpMedicationCalculator({medication,close,record,openProtocol}:Props){
  const medicationAgents=useMemo(()=>Array.from(new Set(medication.paths.map(x=>x.agent))),[medication]),
    [step,setStep]=useState<Step>("medication"),[path,setPath]=useState<GenericDosePath|null>(null),[selectedAgent,setSelectedAgent]=useState(medicationAgents.length===1?medicationAgents[0]:""),
    [age,setAge]=useState(""),[ageUnit,setAgeUnit]=useState<AgeUnit>("years"),[weight,setWeight]=useState(""),[weightUnit,setWeightUnit]=useState<"kg"|"lb">("kg"),
    [route,setRoute]=useState(""),[vialAmount,setVialAmount]=useState(""),[vialVolume,setVialVolume]=useState(""),[medConfirmed,setMedConfirmed]=useState(false),[concConfirmed,setConcConfirmed]=useState(false),
    [contraChecks,setContraChecks]=useState<boolean[]>([]),[specialChecks,setSpecialChecks]=useState<boolean[]>([]),[basePhysician,setBasePhysician]=useState(""),[baseApproved,setBaseApproved]=useState(false),
    [actual,setActual]=useState(""),[administrations,setAdministrations]=useState<LocalAdministration[]>([]),[readyForAnother,setReadyForAnother]=useState(false),[now,setNow]=useState(Date.now());
  const ageYears=ageUnit==="years"?Number(age):ageUnit==="months"?Number(age)/12:Number(age)/365.25,
    kg=weightUnit==="kg"?Number(weight):Number(weight)/2.20462,
    needsWeight=!!path&&(path.formula.kind==="perKg"||path.requiresWeight),routeChoices=path?routesFor(path.route):[],selectedRoute=route||routeChoices[0]||"",
    needsConcentration=!!path&&path.formula.kind!=="instruction"&&path.formula.unit!=="mL"&&path.formula.unit!=="drops"&&path.formula.unit!=="sprays"&&path.formula.unit!=="device"&&(!!path.volumeRequired||!!path.suggestedConcentration)&&(!["ODT","PO","Sublingual","PO — chew"].includes(selectedRoute)||!!path.suggestedConcentration),
    agentPaths=medication.paths.filter(x=>x.agent===selectedAgent),agentConcentrationPath=agentPaths.find(x=>x.formula.kind!=="instruction"&&!["mL","drops","sprays","device"].includes(x.formula.unit)&&(!!x.volumeRequired||!!x.suggestedConcentration)),
    agentNeedsConcentration=!!agentConcentrationPath,concentrationUnit=agentConcentrationPath?.formula.kind!=="instruction"?agentConcentrationPath?.formula.unit:"mg",
    conc=Number(vialAmount)/Number(vialVolume),medicationCheckComplete=!!selectedAgent&&medConfirmed&&(!agentNeedsConcentration||(Number(vialAmount)>0&&Number(vialVolume)>0&&conc>0&&concConfirmed)),eligibility=path?genericEligibilityReason(path,ageYears,kg):"",
    result=useMemo(()=>path?calculateGenericDose(path,ageYears,kg,medication.id):null,[path,ageYears,kg,medication.id]),volume=result&&needsConcentration&&conc>0?result.dose/conc:result?.unit==="mL"?result.dose:0,
    patientText=age!==""?`${age} ${ageUnit}${needsWeight&&kg>0?` • ${fmt(kg)} kg`:""}`:"",contraindications=path?applicableContraindications(medication,path):[],specialChecksText=applicableSpecialChecks(path),
    safetyComplete=contraindications.every((_,i)=>contraChecks[i])&&specialChecksText.every((_,i)=>specialChecks[i])&&(!path?.baseContact||(baseApproved&&!!basePhysician.trim())),
    actualDose=Number(actual),doseMaximum=nextDoseMaximum(path,result,kg,administrations),actualOk=!!result&&result.numeric&&actualDose>0&&actualDose<=doseMaximum,
    belowProtocolMin=!!result&&result.numeric&&!!result.minDose&&actualDose>0&&actualDose<result.minDose,actualVolume=actualOk?(result?.unit==="mL"?actualDose:needsConcentration?actualDose/conc:0):0,
    totalDose=administrations.reduce((n,x)=>n+x.dose,0),totalVolume=administrations.reduce((n,x)=>n+x.volume,0),maxAdministrations=path?.openEndedRepeats?Number.MAX_SAFE_INTEGER:path?.maxAdministrations||1,
    repeatRemaining=Math.max(0,maxAdministrations-administrations.length),lastAdministration=administrations.at(-1),secondsLeft=path?.repeatAfterMinutes&&lastAdministration?Math.max(0,Math.ceil((lastAdministration.time+path.repeatAfterMinutes*60000-now)/1000)):0,
    repeatAllowed=!!path&&repeatRemaining>0&&administrations.length>0&&doseMaximum>0,monitoring=path?monitoringFor(medication.id,path):[],
    additionalAdjustment=(medication.id==="diazepam"||medication.id==="lorazepam")&&path?.patient==="adult"&&(ageYears>65||kg<50)?"DMP 9070 half-dose applied for age over 65 or adult weight under 50 kg":medication.id==="antipsychotics"&&ageYears>=65?"DMP 9045 elderly dose reduced by one-half":(medication.id==="morphine"||medication.id==="hydromorphone")&&ageYears>=65?"DMP 9230 elderly starting dose reduced by one-half":"";

  useEffect(()=>{if(!secondsLeft)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[secondsLeft]);
  const choosePath=(next:GenericDosePath)=>{setPath(next);setRoute(routesFor(next.route)[0]||"");setAge("");setWeight("");setContraChecks([]);setSpecialChecks([]);setBaseApproved(false);setBasePhysician("");setAdministrations([]);setReadyForAnother(false)};
  const finishPatient=()=>{if(path&&!eligibility&&age!==""){if(needsWeight)setStep("weight");else{if(result)setActual(String(result.minDose||result.dose));setStep("safety")}}};
  const finishWeight=()=>{if(path&&result&&!eligibility&&kg>0){setActual(String(result.minDose||result.dose));setStep("safety")}};
  const showResult=()=>{if(result){setActual(String(nextDoseMaximum(path,result,kg,administrations)||result.minDose||result.dose));setStep("result")}};
  const recordNow=()=>{if(!path||!result||administrations.length>=maxAdministrations)return;const amount=result.numeric?actualDose:1,entryVolume=result.unit==="mL"?amount:needsConcentration?actualVolume:0,time=Date.now();record({drug:path.agent,reason:path.label,route:selectedRoute,dose:amount,unit:result.numeric?`${result.unit}${medication.id==="dopamine"?"/min":""}`:"treatment",volume:entryVolume,time,concentration:needsConcentration?`${fmt(conc)} ${result.unit}/mL`:path.administration,patient:patientText,baseAuthorization:path.baseContact?{physician:basePhysician,time,reason:path.baseContact}:undefined});setAdministrations(x=>[...x,{dose:amount,volume:entryVolume,time}]);setReadyForAnother(false);setNow(time)};
  const prepareRepeat=()=>{if(!path||!result||!repeatAllowed||secondsLeft)return;setActual(String(doseMaximum));setReadyForAnother(true)};
  const totalSteps=needsWeight?5:4,stepNumber=step==="medication"?1:step==="patient"?2:step==="weight"?3:step==="safety"?(needsWeight?4:3):(needsWeight?5:4);
  const back=()=>setStep(step==="patient"?"medication":step==="weight"?"patient":step==="safety"?(needsWeight?"weight":"patient"):"safety");

  return <div className="generic-calc-backdrop"><main className="generic-calc" role="dialog" aria-modal="true" aria-label={`${medication.name} calculator`}>
    {path&&<nav className="patient-strip generic-patient-strip" aria-label="Current medication calculation"><button onClick={()=>setStep("medication")}><small>MED</small><b>{path.agent}</b>{conc>0&&<span>{fmt(conc)} {result?.unit||concentrationUnit}/mL</span>}</button><button onClick={()=>setStep("patient")}><small>USE</small><b>{path.label}</b></button>{patientText&&<button onClick={()=>setStep("patient")}><small>PATIENT</small><b>{path.patient==="adult"?"Adult":path.patient==="pediatric"?"Pediatric":"All ages"} • {patientText}</b></button>}{selectedRoute&&<button onClick={()=>setStep("patient")}><small>ROUTE</small><b>{selectedRoute}</b></button>}</nav>}
    <div className="wizard-top generic-wizard-top"><button className="back" onClick={step==="medication"?close:back}>‹ Back</button><span>Step {stepNumber} of {totalSteps}</span><button className="start-over" onClick={openProtocol}>Protocol §</button></div>
    <div className="progress generic-progress" aria-label={`Step ${stepNumber} of ${totalSteps}`}><i style={{width:`${stepNumber/totalSteps*100}%`}}/></div>
    <div className="clinical-banner"><b>DMP verified</b><span>July 2026 • Medication {medication.protocolId}</span></div>
    <section className="wizard-card generic-body">
      {step==="medication"&&<><small className="eyebrow">MEDICATION CHECK</small><h1>Confirm the medication in your hand</h1><p className="screen-help">Compare the physical medication with the selected medication.</p>{medicationAgents.length>1&&<div className="route-grid generic-agent-picker">{medicationAgents.map(x=><button key={x} className={selectedAgent===x?"selected":""} onClick={()=>{setSelectedAgent(x);setPath(null);setVialAmount("");setVialVolume("");setMedConfirmed(false);setConcConfirmed(false)}}>{x}</button>)}</div>}{selectedAgent&&<><div className="scan-confirm-card"><div className="scan-med-photo"><div className="reference-vial"><small>{selectedAgent.toUpperCase()}</small><b>Rx</b><span>Physical medication</span></div></div><div className="scan-med-identity"><small>MANUAL SELECTION</small><h2>{selectedAgent}</h2><p>DMP {medication.protocolId}</p><span className="manual-vial-note">Enter the concentration from the physical medication below.</span></div></div>{agentNeedsConcentration&&<><h3 className="label-heading">Enter exactly what the physical label says</h3><div className="vial-entry"><label><span>Total drug</span><div><input inputMode="decimal" value={vialAmount} onChange={e=>{setVialAmount(e.target.value);setConcConfirmed(false)}} placeholder="0"/><b>{concentrationUnit}</b></div></label><label><span>Total volume</span><div><input inputMode="decimal" value={vialVolume} onChange={e=>{setVialVolume(e.target.value);setConcConfirmed(false)}} placeholder="0"/><b>mL</b></div></label></div>{Number(vialAmount)>0&&Number(vialVolume)>0&&<div className="manual-concentration-result"><span>Calculated concentration — confirm only after both label values are complete</span><b>{fmt(conc)} {concentrationUnit}/mL</b></div>}{agentConcentrationPath?.suggestedConcentration&&<div className="input-guidance"><b>Common DMP stock/reference</b><span>{fmt(agentConcentrationPath.suggestedConcentration)} {agentConcentrationPath.concentrationUnit||`${concentrationUnit}/mL`}. Confirm the physical label; do not rely on this reference.</span></div>}</>}<div className="scan-confirm-checks compact-confirmations"><label className={medConfirmed?"checked":""}><input type="checkbox" checked={medConfirmed} onChange={e=>setMedConfirmed(e.target.checked)}/><span><b>Medication matches</b>{selectedAgent}</span></label>{agentNeedsConcentration&&<label className={concConfirmed?"checked":""}><input type="checkbox" checked={concConfirmed} disabled={!(Number(vialAmount)>0&&Number(vialVolume)>0&&conc>0)} onChange={e=>setConcConfirmed(e.target.checked)}/><span><b>Concentration matches</b>{conc>0?`${vialAmount} ${concentrationUnit} / ${vialVolume} mL`:"Enter label values"}</span></label>}</div></>}<button className="continue" disabled={!medicationCheckComplete} onClick={()=>setStep("patient")}>Continue to patient information <span>→</span></button></>}

      {step==="patient"&&<><small className="eyebrow">PATIENT INFORMATION</small><h1>{path?"Enter only what affects this dose":`Why is ${selectedAgent} being given?`}</h1><p className="screen-help">Only choices that apply to the confirmed medication are shown.</p>{!path?<div className="stack">{agentPaths.map(x=><button className="big-choice" key={x.id} onClick={()=>choosePath(x)}><span>{x.label}</span><i>›</i></button>)}</div>:<><div className="selected-generic-path"><span><small>INDICATION</small><b>{path.label}</b></span><button onClick={()=>{setPath(null);setAge("");setWeight("")}}>Change</button></div>{routeChoices.length>1&&<><h3 className="route-label">Approved route</h3><div className="route-grid">{routeChoices.map(x=><button key={x} className={route===x?"selected":""} onClick={()=>setRoute(x)}>{x}</button>)}</div></>}<label className="giant-input"><span>Patient age</span><input autoFocus inputMode="decimal" value={age} onChange={e=>setAge(e.target.value)} placeholder="0"/></label><div className="age-unit-toggle">{(["years","months","days"] as AgeUnit[]).map(x=><button key={x} className={ageUnit===x?"selected":""} onClick={()=>setAgeUnit(x)}>{x}</button>)}</div>{age!==""&&<div className="classification"><span>DMP classification</span><b>{path.patient==="adult"?"Adult":path.patient==="pediatric"?"Pediatric":"All ages"}</b></div>}{eligibility&&age!==""&&<div className="hard-stop" role="alert"><b>THIS PATHWAY DOES NOT APPLY</b><span>{eligibility}</span><button className="hard-stop-recovery" onClick={()=>{setPath(null);setAge("")}}>Choose the correct pathway →</button></div>}<button className="continue" disabled={!age||!!eligibility} onClick={finishPatient}>Continue to {needsWeight?"weight":"safety checks"} <span>→</span></button></>}</>}

      {step==="weight"&&path&&<><small className="eyebrow">CALCULATION WEIGHT</small><h1>What is the patient’s weight?</h1><p className="screen-help">Kilograms remain visible and are used for all dose calculations.</p><div className="unit-toggle"><button className={weightUnit==="kg"?"selected":""} onClick={()=>{setWeightUnit("kg");setWeight("")}}>Kilograms</button><button className={weightUnit==="lb"?"selected":""} onClick={()=>{setWeightUnit("lb");setWeight("")}}>Pounds</button></div><label className="giant-input"><span>Patient weight ({weightUnit})</span><input autoFocus inputMode="decimal" value={weight} onChange={e=>setWeight(e.target.value)} placeholder="0"/></label>{kg>0&&<div className="classification"><span>Calculation weight</span><b>{fmt(kg)} kg</b></div>}{eligibility&&weight!==""&&<div className="hard-stop" role="alert"><b>WEIGHT DOES NOT MATCH THIS PATHWAY</b><span>{eligibility}</span><button className="hard-stop-recovery" onClick={()=>{setStep("patient");setPath(null);setWeight("")}}>Choose the correct pathway →</button></div>}<button className="continue" disabled={!(kg>0)||!!eligibility} onClick={finishWeight}>Continue to safety checks <span>→</span></button></>}

      {step==="safety"&&path&&result&&<><small className="eyebrow">SAFETY CHECK</small><h1>Confirm before calculating</h1><p className="screen-help">Every item below is specific to this medication pathway.</p><div className="action-line"><small>DMP DOSE</small><b>{selectedRoute}</b><strong>{result.text}{needsConcentration?` = ${fmt(volume)} mL`:""}</strong></div><div className="safety-list">{contraindications.map((x,i)=><label className={contraChecks[i]?"checked":""} key={x}><input type="checkbox" checked={!!contraChecks[i]} onChange={e=>setContraChecks(c=>{const n=[...c];n[i]=e.target.checked;return n})}/><span><b>{i+1}</b>{x} is not present or has been addressed</span></label>)}{specialChecksText.map((x,i)=><label className={specialChecks[i]?"checked":""} key={x}><input type="checkbox" checked={!!specialChecks[i]} onChange={e=>setSpecialChecks(c=>{const n=[...c];n[i]=e.target.checked;return n})}/><span><b>{contraindications.length+i+1}</b>{x}</span></label>)}</div>{path.baseContact&&<div className="generic-base"><b>BASE CONTACT REQUIRED</b><span>{path.baseContact}</span><input placeholder="Approving physician name" value={basePhysician} onChange={e=>{setBasePhysician(e.target.value);setBaseApproved(false)}}/><label><input type="checkbox" checked={baseApproved} onChange={e=>setBaseApproved(e.target.checked)}/><span>Direct verbal order received and read back</span></label></div>}<div className={safetyComplete?"generic-check-progress complete":"generic-check-progress"}><b>{contraChecks.filter(Boolean).length+specialChecks.filter(Boolean).length} of {contraindications.length+specialChecksText.length} checks confirmed</b><span>{safetyComplete?"Safety checklist complete.":"Confirm every applicable item to continue."}</span></div><button className="continue" disabled={!safetyComplete} onClick={showResult}>Continue to final dose <span>→</span></button></>}

      {step==="result"&&path&&result&&<>
        <small className="eyebrow">FINAL CROSS-CHECK</small><h1>{administrations.length?"Administration tracker":"Dose ready"}</h1>
        <div className="entered-summary"><header><small>ENTERED INFORMATION</small><b>Tap Back to correct</b></header><div><button onClick={()=>setStep("medication")}><small>MEDICATION</small><b>{path.agent}</b></button><button onClick={()=>setStep("medication")}><small>CONCENTRATION</small><b>{needsConcentration?`${fmt(conc)} ${result.unit}/mL`:"Non-volume form"}</b></button><button className="summary-indication" onClick={()=>setStep("patient")}><small>INDICATION</small><b>{path.label}</b></button><button onClick={()=>setStep("patient")}><small>PATIENT</small><b>{patientText}</b></button><button onClick={()=>setStep("patient")}><small>ROUTE</small><b>{selectedRoute}</b></button></div></div>
        {additionalAdjustment&&<div className="generic-dose-adjustment"><b>MEDICATION-SPECIFIC ADJUSTMENT</b><span>{additionalAdjustment}</span></div>}
        <div className="action-line"><small>{administrations.length?"NEXT DOSE":"INITIAL DOSE"}</small><b>{selectedRoute}</b><strong>{result.numeric?(result.minDose?`PROTOCOL DOSE ${result.text}`:`GIVE ${fmt(result.dose)} ${result.unit}${needsConcentration?` = DRAW ${fmt(result.dose/conc)} mL`:""}`):result.text}</strong></div>
        <div className="monitoring-cautions"><small>MONITORING & ADMINISTRATION</small><ul>{monitoring.map(x=><li key={x}>{x}</li>)}</ul></div>
        {administrations.length>0&&<div className="generic-administration-log"><header><span><small>TOTAL GIVEN</small><b>{fmt(totalDose)} {result.numeric?result.unit:"treatment"}</b></span><span><small>TOTAL VOLUME</small><b>{needsConcentration||result.unit==="mL"?`${fmt(totalVolume)} mL`:"N/A"}</b></span></header>{administrations.map((x,i)=><p key={x.time}><b>Dose {i+1}</b><span>{fmt(x.dose)} {result.numeric?result.unit:"treatment"}{x.volume?` • ${fmt(x.volume)} mL`:""}</span><time>{new Date(x.time).toLocaleTimeString()}</time></p>)}</div>}
        {(!administrations.length||readyForAnother)&&result.numeric&&<label className="giant-input actual-generic"><span>Actual amount being given ({result.unit}{medication.id==="dopamine"?"/min":""})</span><input inputMode="decimal" value={actual} onChange={e=>setActual(e.target.value)}/></label>}
        {actualOk&&needsConcentration&&(!administrations.length||readyForAnother)&&<div className="classification"><span>Actual volume</span><b>{fmt(actualVolume)} mL</b></div>}
        {belowProtocolMin&&(!administrations.length||readyForAnother)&&<div className="generic-dose-adjustment"><b>BELOW THE LISTED DMP DOSE RANGE</b><span>The entered amount will be documented exactly as given. Recheck the protocol dose and clinical reason before recording.</span></div>}
        {(!administrations.length||readyForAnother)&&result.numeric&&!actualOk&&<div className="hard-stop"><b>CHECK ACTUAL DOSE</b><span>Enter more than 0 and no more than {fmt(doseMaximum)} {result.unit}.</span></div>}
        {(!administrations.length||readyForAnother)?<button className="initial-record-dose" disabled={result.numeric&&!actualOk} onClick={recordNow}><span><small>{administrations.length?"ADDITIONAL DOSE":"INITIAL DOSE"}</small><b>{selectedRoute}</b></span><strong>{result.numeric?`GIVE ${fmt(actualDose)} ${result.unit}${needsConcentration?` = DRAW ${fmt(actualVolume)} mL`:""}`:"Record treatment completed"}</strong><em>Give and record now</em></button>:repeatAllowed?<div className="generic-repeat"><b>{path.openEndedRepeats?"Additional protocol dose available":`${repeatRemaining} protocol dose${repeatRemaining===1?"":"s"} available`}</b><span>{path.repeat}</span><button disabled={secondsLeft>0} onClick={prepareRepeat}>{secondsLeft>0?`Reassess — repeat available in ${Math.floor(secondsLeft/60)}:${String(secondsLeft%60).padStart(2,"0")}`:"Reassessed — prepare next dose"}</button></div>:<div className="generic-repeat complete"><b>No additional standing dose available here</b><span>{path.repeat}</span></div>}
        <details className="full-cross-check"><summary>Show full medication cross-check</summary><div className="generic-summary"><p><span>Medication</span><b>{path.agent}</b></p><p><span>Indication</span><b>{path.label}</b></p><p><span>Patient / route</span><b>{patientText} • {selectedRoute}</b></p>{needsConcentration&&<p><span>Concentration</span><b>{fmt(conc)} {result.unit}/mL</b></p>}<p><span>Administration</span><b>{path.administration}</b></p><p><span>Repeat rule</span><b>{path.repeat}</b></p><p><span>Protocol</span><b>DMP {medication.protocolId} • {path.protocol}</b></p>{path.baseContact&&<p><span>Base authorization</span><b>Approved by {basePhysician}</b></p>}</div></details>
        <button className="new-calc" onClick={close}>{administrations.length?"Return to medication list":"Close without recording"}</button>
      </>}
    </section>
  </main></div>;
}

export function calculateGenericDose(path:GenericDosePath,age:number,weight:number,medicationId:string){
  const f=path.formula;if(f.kind==="instruction")return{numeric:false,dose:0,minDose:0,unit:f.unit,text:f.text};let dose=0,minDose=0,unit=f.unit;
  if(f.kind==="fixed")dose=f.amount;if(f.kind==="range"){dose=f.max;minDose=f.min}if(f.kind==="perKg")dose=Math.min(f.max??Infinity,Math.max(f.min??0,weight*f.amount));if(f.kind==="ageBands")dose=f.bands.find(x=>age>=x.min&&age<x.max)?.amount||0;
  if(medicationId==="diltiazem"&&age>65){dose*=.5;dose=Math.min(dose,path.id==="initial"?10:20)}if(medicationId==="antipsychotics"&&age>=65)dose*=.5;if((medicationId==="diazepam"||medicationId==="lorazepam")&&path.patient==="adult"&&(age>65||weight<50)){dose*=.5;minDose*=.5}if((medicationId==="morphine"||medicationId==="hydromorphone")&&age>=65){dose*=.5;minDose*=.5}
  const rate=medicationId==="dopamine"?"/min":"";return{numeric:true,dose,minDose,unit,text:f.kind==="range"?`${fmt(minDose)}–${fmt(dose)} ${unit}`:`${fmt(dose)} ${unit}${rate}`};
}

export function genericEligibilityReason(path:GenericDosePath,age:number,weight:number){
  if(!Number.isFinite(age)||age<0||age>=130)return"Enter a valid patient age.";if(path.patient==="adult"&&age<12)return"This is an adult pathway. Choose the pediatric pathway when one is listed.";if(path.patient==="pediatric"&&age>=12)return"This is a pediatric pathway for patients under 12 years.";
  if(path.minAge!==undefined&&age<path.minAge)return`DMP ${path.label} begins at ${ageLabel(path.minAge)}.`;if(path.maxAge!==undefined&&age>=path.maxAge)return`This pathway applies below ${ageLabel(path.maxAge)}.`;if(path.id==="ped-hypo-small"&&weight>=25)return"This Glucagon pathway is for patients under 25 kg.";if(path.id==="ped-hypo-large"&&weight>0&&weight<25)return"This Glucagon pathway is for patients 25 kg or greater.";if(path.id==="poison-adult"&&weight>0&&weight<40)return"The adult organophosphate pathway requires a weight of 40 kg or greater. Choose the under-40 kg pathway.";return"";
}

function applicableContraindications(medication:GenericMedication,path:GenericDosePath){
  if(medication.id==="antiemetics"){if(path.agent.includes("Promethazine"))return["Respiratory or CNS depression","Sulfite allergy","Patient is under 2 years"];if(path.agent.includes("Metoclopramide"))return["Suspected bowel obstruction","Patient is under 8 years"];if(path.agent.includes("Droperidol"))return["Suspected acute myocardial infarction or acute coronary syndrome","Systolic BP under 100 mmHg or no palpable radial pulse","Respiratory depression","Known QTc prolongation","Pregnancy"];return["First-trimester pregnancy without severe dehydration and intractable vomiting"]}
  if(medication.id==="atropine")return path.id.startsWith("brady")?medication.contraindications:medication.contraindications.filter(x=>!x.includes("stable bradycardia"));if((medication.id==="morphine"||medication.id==="hydromorphone")&&path.patient==="adult")return medication.contraindications.filter(x=>!x.includes("Age under")&&!x.includes("pediatric"));return medication.contraindications.filter(x=>!/^Age under/i.test(x)&&!/^Not indicated for pediatric/i.test(x));
}

function applicableSpecialChecks(path:GenericDosePath|null){return(path?.special||[]).filter(x=>!x.includes("Under 6 months requires Base")&&!x.includes("Select the medication-specific over-65 adjustment"))}

function monitoringFor(id:string,path:GenericDosePath){
  if(path.monitoring?.length)return path.monitoring;const first=path.administration;
  if(id==="amiodarone"||id==="diltiazem"||id==="dopamine")return[first,"Continuous ECG and frequent blood-pressure/perfusion reassessment.","Stop and reassess for hypotension, bradycardia or worsening dysrhythmia."];
  if(id==="antipsychotics"||id==="diazepam"||id==="lorazepam")return[first,"Continuous ECG, SpO₂ and ventilation monitoring; waveform capnography when available.","Reassess sedation score, airway, respiratory rate and blood pressure before any additional dose."];
  if(id==="morphine"||id==="hydromorphone")return[first,"Continuous pulse oximetry; monitor ventilation, blood pressure and analgesic response.","Keep airway equipment and naloxone immediately available; reassess before every additional dose."];
  if(id==="naloxone")return[first,"Titrate to adequate ventilation rather than full arousal when possible.","Monitor for recurrent respiratory depression, withdrawal, vomiting and pulmonary edema."];
  if(id==="nitroglycerin")return[first,"Reassess blood pressure, perfusion and symptoms before every dose.","Stop if hypotension develops or protocol prerequisites are no longer met."];
  if(id==="dextrose"||id==="glucagon"||id==="oral-glucose")return[first,"Recheck glucose and neurologic status after treatment.","Continue airway and aspiration precautions until mental status normalizes."];
  if(id==="ipratropium"||id==="racemic-epinephrine")return[first,"Monitor work of breathing, breath sounds, SpO₂ and heart rate.","Reassess for improvement or worsening respiratory fatigue during transport."];
  return[first,"Reassess indication-specific vital signs and clinical response after administration.","Document the dose, route, time, response and any adverse effect in the ePCR."];
}

function nextDoseMaximum(path:GenericDosePath|null,result:ReturnType<typeof calculateGenericDose>|null,weight:number,entries:LocalAdministration[]){
  if(!path||!result||!result.numeric)return 0;const total=entries.reduce((n,x)=>n+x.dose,0);let ceiling=Infinity;if(path.maxCumulative!==undefined)ceiling=path.maxCumulative;if(path.maxCumulativePerKg!==undefined)ceiling=Math.min(ceiling,path.maxCumulativePerKg*weight);if(path.absoluteCumulativeMax!==undefined)ceiling=Math.min(ceiling,path.absoluteCumulativeMax);return Math.max(0,Math.min(result.dose,ceiling-total));
}

function routesFor(route:string){const map:Record<string,string[]>={"IV/IM/PO/ODT":["IV","IM","PO","ODT"],"IV/PO/ODT":["IV","PO","ODT"],"IV/IO/IM/IN":["IV/IO","IM","IN"],"IV/IO/IM":["IV/IO","IM"],"IV/IM":["IV","IM"],"Slow IV/IM":["IV","IM"],"IM or ODT":["IM","ODT"]};return map[route]||[route]}
function ageLabel(years:number){return years<1?`${Math.round(years*12)} months`:`${fmt(years)} years`}
function fmt(n:number){const d=Math.abs(n)>0&&Math.abs(n)<1?3:2;return Number.isFinite(n)?Number(n.toFixed(d)).toString():"—"}
