import {useEffect,useMemo,useState} from "react";
import type {GenericTreatmentContext} from "./DmpMedicationCalculator";
import CalculationBoard, {type CalculationBox} from "./CalculationBoard";
import WeightQuickSelect from "./WeightQuickSelect";
import DoseSyringe from "./DoseSyringe";
import type {EncounterPatient} from "./VersedBuilder";
import "./versedBuilder.css";
import "./versedForm.css";
import "./versedConsole.css";
import "./fentanylBuilder.css";

type RecordedAdministration={drug:string;reason:string;route:string;dose:number;unit:string;volume:number;time:number;concentration:string;patient?:string;baseAuthorization?:{physician:string;time:number;reason:string}};
type MedicationOption={id:string;name:string;brand:string;released:boolean};
type Props={close:()=>void;record:(entry:RecordedAdministration)=>void;onContextChange:(context:GenericTreatmentContext|null)=>void;medicationOptions:MedicationOption[];selectMedication:(id:string,patient?:EncounterPatient)=>void;initialPatient?:EncounterPatient|null};
type Stage="medication"|"concentration"|"indication"|"route"|"patient"|"dose"|"safety"|"result";
type PatientGroup="adult"|"older"|"pediatric"|"infant"|"";
type Administration={dose:number;volume:number;time:number};

const indication="Moderate to severe pain in a hemodynamically stable patient";
const safetyItems=[
  "The patient is hemodynamically stable with no signs of shock.",
  "No respiratory depression is present; ventilation can be continuously monitored.",
  "No benzodiazepine is being coadministered unless a direct physician verbal order has been received.",
  "Continuous pulse oximetry, resuscitation equipment and naloxone are immediately available.",
  "Medication, concentration, route, weight, dose and volume have been verbally repeated back.",
];
const routes=["IV/IO","IM","IN"];
const fmt=(value:number)=>Number.isFinite(value)?Number(value.toFixed(Math.abs(value)<1?2:1)).toString():"—";

export default function FentanylBuilder({close,record,onContextChange,medicationOptions,selectMedication,initialPatient}:Props){
  const initialGroup:PatientGroup=initialPatient?.patient==="adult"?"adult":initialPatient?.patient==="pediatric"?"pediatric":"";
  const [stage,setStage]=useState<Stage>("result"),[medConfirmed,setMedConfirmed]=useState(true),[concentration,setConcentration]=useState<number|null>(null),[customAmount,setCustomAmount]=useState(""),[customVolume,setCustomVolume]=useState(""),[labelConfirmed,setLabelConfirmed]=useState(false),[route,setRoute]=useState(""),
    [patientGroup,setPatientGroup]=useState<PatientGroup>(initialGroup),[weightKg,setWeightKg]=useState(initialPatient?.weightKg||0),[weightSource,setWeightSource]=useState(initialPatient?.weightKg?"carried from current patient":""),[doseRate,setDoseRate]=useState<number|null>(null),
    [basePhysician,setBasePhysician]=useState(""),[baseConfirmed,setBaseConfirmed]=useState(false),[safetyConfirmed,setSafetyConfirmed]=useState(false),[plannedDose,setPlannedDose]=useState(""),[editingDose,setEditingDose]=useState(false),[administrations,setAdministrations]=useState<Administration[]>([]),[now,setNow]=useState(Date.now()),[addingMedication,setAddingMedication]=useState(false);
  const customConcentration=Number(customAmount)>0&&Number(customVolume)>0?Number(customAmount)/Number(customVolume):0;
  const pediatric=patientGroup==="pediatric"||patientGroup==="infant",infant=patientGroup==="infant",older=patientGroup==="older";
  const effectiveRate=route==="IN"&&pediatric?2:doseRate;
  const baseDose=weightKg>0&&effectiveRate?weightKg*effectiveRate:0,protocolDose=older?baseDose/2:baseDose,maxTotal=weightKg>0?(route==="IN"?4:3)*weightKg:0,totalGiven=administrations.reduce((sum,item)=>sum+item.dose,0),remaining=Math.max(0,maxTotal-totalGiven),nextDoseMaximum=Math.min(protocolDose,remaining),repeatMinutes=route==="IN"?10:5,lastTime=administrations.at(-1)?.time||0,secondsLeft=lastTime?Math.max(0,Math.ceil((lastTime+repeatMinutes*60_000-now)/1000)):repeatMinutes*60,timerText=`${String(Math.floor(secondsLeft/60)).padStart(2,"0")}:${String(secondsLeft%60).padStart(2,"0")}`;
  const selectedDose=Number(plannedDose),selectedDoseValid=selectedDose>0&&selectedDose<=nextDoseMaximum,volume=concentration&&selectedDoseValid?selectedDose/concentration:0,inVolumeBlocked=route==="IN"&&volume>2;
  const patientComplete=!!patientGroup&&weightKg>0&&(!infant||(!!basePhysician.trim()&&baseConfirmed)),doseComplete=!!effectiveRate&&protocolDose>0;
  const calculationReady=medConfirmed&&!!concentration&&labelConfirmed&&!!route&&patientComplete&&doseComplete&&safetyConfirmed&&!inVolumeBlocked&&remaining>0;
  const recorded=administrations.length>0,repeatAvailable=recorded&&secondsLeft===0&&remaining>0;
  const hasStarted=medConfirmed||!!concentration||!!route||!!patientGroup;
  const patientLabel=patientGroup==="adult"?`Adult • ${fmt(weightKg*2.20462)} lb (${fmt(weightKg)} kg) estimated`:patientGroup==="older"?`Adult • elderly/frail • ${fmt(weightKg*2.20462)} lb (${fmt(weightKg)} kg)`:patientGroup==="infant"?`Pediatric under 1 • ${fmt(weightKg*2.20462)} lb (${fmt(weightKg)} kg)${weightSource?` • ${weightSource}`:""}`:patientGroup==="pediatric"?`Pediatric 1–11 • ${fmt(weightKg*2.20462)} lb (${fmt(weightKg)} kg)${weightSource?` • ${weightSource}`:""}`:"";
  const visibleMedicationOptions=medicationOptions.filter(option=>option.released);

  useEffect(()=>{if(route==="IN"&&pediatric)setDoseRate(2)},[route,pediatric]);
  useEffect(()=>{if(nextDoseMaximum>0&&!editingDose)setPlannedDose(fmt(nextDoseMaximum))},[nextDoseMaximum,editingDose]);
  useEffect(()=>{if(!lastTime||secondsLeft===0)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[lastTime,secondsLeft]);
  useEffect(()=>{onContextChange({medication:"Fentanyl",indication,route:route||"Route not selected",dose:protocolDose>0?`${fmt(protocolDose)} mcg`:"Pending patient information",volume:volume>0?`${fmt(volume)} mL`:"Pending calculated dose",administration:route==="IN"?"Divide equally between nostrils; maximum 1 mL per nostril.":route==="IM"?"Administer IM; IV is preferred for accurate titration.":"Administer slowly and titrate to tolerable pain.",repeat:`Reassess after ${repeatMinutes} minutes. Maximum cumulative ${route==="IN"?4:3} mcg/kg.`,monitoring:["Continuous pulse oximetry and respiratory reassessment.","Keep naloxone and resuscitation equipment immediately available."],protocolId:"9230",protocolName:"Opioids / Fentanyl",protocolPage:163});return()=>onContextChange(null)},[route,protocolDose,volume,repeatMinutes,onContextChange]);

  const resetDownstream=()=>{setSafetyConfirmed(false);setEditingDose(false)};
  const choosePatient=(group:PatientGroup)=>{setPatientGroup(group);setWeightKg(0);setWeightSource("");setBasePhysician("");setBaseConfirmed(false);setDoseRate(route==="IN"&&(group==="pediatric"||group==="infant")?2:null);resetDownstream()};
  const giveNow=()=>{if(!calculationReady||!selectedDoseValid||!concentration||inVolumeBlocked)return;const time=Date.now(),givenVolume=selectedDose/concentration;record({drug:"Fentanyl",reason:indication,route,dose:selectedDose,unit:"mcg",volume:givenVolume,time,concentration:`${fmt(concentration)} mcg/mL`,patient:patientLabel,baseAuthorization:infant?{physician:basePhysician.trim(),time,reason:"Fentanyl for pediatric patient under 1 year"}:undefined});setAdministrations(items=>[...items,{dose:selectedDose,volume:givenVolume,time}]);setNow(time);setEditingDose(false)};
  const editBox=(next:Stage)=>{if(!recorded)setStage(next)};
  const patientSnapshot:EncounterPatient|undefined=patientGroup?{patient:pediatric?"pediatric":"adult",weightKg,halfDose:older}:undefined;
  const board:CalculationBox[]=[
    {id:"concentration",label:"CONCENTRATION",value:concentration?`${fmt(concentration)} mcg/mL`:"",detail:labelConfirmed?"Physical label confirmed":"Confirm physical label",complete:!!concentration&&labelConfirmed,active:stage==="concentration",available:!recorded,onClick:()=>editBox("concentration"),quickChoices:recorded?[]:[{label:"50 mcg/mL",selected:concentration===50&&labelConfirmed,onClick:()=>{setConcentration(50);setLabelConfirmed(true);resetDownstream();setStage("result")}},{label:"Custom",selected:concentration===0,onClick:()=>{setConcentration(0);setLabelConfirmed(false);setStage("concentration")}}]},
    {id:"indication",label:"INDICATION",value:"Pain management",detail:"Single DMP indication auto-filled",complete:true,notRequired:true,active:stage==="indication",available:!recorded,onClick:()=>editBox("indication")},
    {id:"route",label:"ROUTE",value:route,detail:route?"Approved route selected":"Select approved route",complete:!!route,active:stage==="route",available:!recorded,onClick:()=>editBox("route"),quickChoices:recorded?[]:routes.map(value=>({label:value,selected:route===value,onClick:()=>{setRoute(value);if(value==="IN"&&pediatric)setDoseRate(2);resetDownstream();setStage("result")}}))},
    {id:"patient",label:"PATIENT",value:patientComplete?patientLabel:"",detail:patientComplete?"Patient and calculation weight selected":"Select patient and weight",complete:patientComplete,active:stage==="patient",available:!recorded,onClick:()=>editBox("patient"),quickChoices:recorded?[]:[{label:"Adult",selected:patientGroup==="adult",onClick:()=>{choosePatient("adult");setStage("patient")}},{label:"Frail",selected:patientGroup==="older",onClick:()=>{choosePatient("older");setStage("patient")}},{label:"Pediatric",selected:pediatric,onClick:()=>{choosePatient("pediatric");setStage("patient")}}]},
    {id:"dose",label:"DOSE",value:doseComplete?`${fmt(effectiveRate||0)} mcg/kg • ${fmt(protocolDose)} mcg`:"",detail:doseComplete?(older?"Half starting dose applied":"Protocol starting dose selected"):"Select starting dose",complete:doseComplete,active:stage==="dose",available:!recorded&&patientComplete,onClick:()=>editBox("dose")},
    {id:"safety",label:"SAFETY",value:"All checks confirmed",detail:safetyConfirmed?"One confirmation":"Review complete safety list",complete:safetyConfirmed,active:stage==="safety",available:!recorded,onClick:()=>editBox("safety")},
  ];
  const medicationReference=medConfirmed?<aside className="versed-medication-reference fentanyl-medication-reference" aria-label="Selected Fentanyl reference image"><div className="versed-reference-vial fentanyl-reference-vial"><small>FENTANYL</small><b>Rx</b><span>INJECTION</span></div><span><small>SELECTED MEDICATION</small><b>Fentanyl</b><em>Opioid analgesic</em></span></aside>:null;

  return <main className="versed-builder fentanyl-builder">
    <div className="versed-builder-top"><button className="drug-back-button" onClick={close}>‹ Back to medications</button><span>FENTANYL FORMAT PILOT</span><button onClick={close}>Start over</button></div>
    <div className={`versed-layout${calculationReady?" calculation-complete":""}`}>
      <header className="builder-medication-banner">{medicationReference}</header>
      <aside className="versed-left-column" aria-label="Calculation controls"><CalculationBoard boxes={board} className="versed-status-board"/><div id="versed-left-tools" className="versed-left-tools" aria-label="Report treatment and protocol tools"/></aside>
      {stage==="result"&&!hasStarted&&<section className="versed-empty-workspace" aria-label="Selection workspace"/>}
      {stage==="result"&&hasStarted&&<section className="versed-dashboard" aria-label="Live Fentanyl dose and repeat information">
        {medicationReference}
        <header className="administration-area-heading"><small>DRUG ADMINISTRATION</small><b>Fentanyl</b><span>{route||"Route pending"}</span></header>
        <section className={calculationReady?"dashboard-primary-dose ready":"dashboard-primary-dose pending"}><small>DOSE AND AMOUNT TO GIVE</small>{calculationReady&&protocolDose>0?<><div className="dashboard-dose-answer"><strong>{selectedDoseValid?`${fmt(selectedDose)} mcg`:"—"}</strong><span>Draw <b>{volume>0?`${fmt(volume)} mL`:"—"}</b></span>{route==="IN"&&volume>0&&<em>{fmt(volume/2)} mL per nostril</em>}</div><p>Protocol-calculated dose: {fmt(protocolDose)} mcg • cumulative maximum {fmt(maxTotal)} mcg</p>{editingDose?<div className="dashboard-dose-editor"><label>Actual dose to give<input autoFocus inputMode="decimal" value={plannedDose} onChange={event=>setPlannedDose(event.target.value)}/><b>mcg</b></label>{!selectedDoseValid&&<span>Enter more than 0 and no more than {fmt(nextDoseMaximum)} mcg.</span>}<button onClick={()=>{setPlannedDose(fmt(nextDoseMaximum));setEditingDose(false)}}>Use calculated dose</button></div>:<button className="dashboard-lower-dose" onClick={()=>setEditingDose(true)}>Change to a lesser dose</button>}</>:<strong className="dashboard-dose-pending">Complete required checks</strong>}</section>
        {calculationReady&&<DoseSyringe volume={volume}/>}
        {calculationReady&&<section className="administration-special"><small>SPECIAL INSTRUCTIONS</small><div><span><b>Route</b>{route}</span><span><b>How to give</b>{route==="IN"?"Divide equally between nostrils.":route==="IM"?"Administer IM; IV is preferred for accurate titration.":"Administer slowly and titrate to tolerable pain."}</span>{route==="IN"&&<span className="wide"><b>Intranasal volume</b>{fmt(volume/2)} mL per nostril • {fmt(volume)} mL total • maximum 1 mL per nostril</span>}<span className="wide"><b>Dose ceiling</b>{fmt(maxTotal)} mcg cumulative maximum • {repeatMinutes}-minute reassessment before repeat</span></div></section>}
        {inVolumeBlocked?<button className="dashboard-required" onClick={()=>setStage("concentration")}><b>IN volume exceeds 1 mL per nostril</b><span>Choose another route or confirm an appropriate higher concentration.</span><i>Correct ›</i></button>:!calculationReady&&<button className="dashboard-required" onClick={()=>setStage(board.find(item=>!item.complete)?.id as Stage||"concentration")}><b>Choose any red box</b><span>Complete checks in the order that is fastest for you.</span><i>Open next check ›</i></button>}
        <button className={recorded?"dashboard-give-now repeat":"dashboard-give-now"} disabled={!calculationReady||!selectedDoseValid||(!repeatAvailable&&recorded)} onClick={giveNow}><small>{recorded?"GIVE NEXT DOSE NOW":"GIVE NOW"}</small><strong>{selectedDoseValid?`${fmt(selectedDose)} mcg • ${fmt(volume)} mL`:"Complete dose"}</strong><span>{route||"Route pending"} • records administration and starts timer</span></button>
        <section className={`dashboard-timer repeat-status ${recorded&&secondsLeft>0?"running":""} ${remaining<=0?"unavailable":""}`}>{remaining<=0?<><small>NO REPEAT AVAILABLE</small><strong>LIMIT</strong><span>Cumulative protocol maximum recorded</span></>:!recorded?<><small>REPEAT DOSE</small><strong>{String(repeatMinutes).padStart(2,"0")}:00</strong><span>Available after reassessment following the first dose</span></>:secondsLeft>0?<><small>REPEAT DOSE AVAILABLE IN</small><strong>{timerText}</strong><span>Reassess pain, ventilation and perfusion first</span><b className="next-dose-field">Up to {fmt(nextDoseMaximum)} mcg • {concentration?fmt(nextDoseMaximum/concentration):"—"} mL</b></>:<><small>REPEAT DOSE</small><strong>AVAILABLE NOW</strong><span>Give only if reassessment confirms it remains indicated</span><b className="next-dose-field">Up to {fmt(nextDoseMaximum)} mcg • {concentration?fmt(nextDoseMaximum/concentration):"—"} mL</b></>}</section>
        {recorded&&<div className="dashboard-recorded"><b>✓ {administrations.length} dose{administrations.length===1?"":"s"} recorded</b><span>{fmt(totalGiven)} of {fmt(maxTotal)} mcg cumulative maximum</span></div>}
        {recorded&&<button className="dashboard-add-med" onClick={()=>{setAddingMedication(true);setStage("medication")}}>+ Additional medication • same patient</button>}
      </section>}
      {stage!=="result"&&<section className="builder-workspace versed-inline-workspace" aria-label={`Edit ${stage}`}>{medicationReference}<button className="versed-inline-close" onClick={()=>setStage("result")} aria-label="Close selection">×</button>
        {stage==="medication"&&<><small className="eyebrow">MEDICATION</small><h1>{addingMedication?"Add medication to this patient":"Select medication"}</h1><p className="screen-help">{addingMedication?"Patient information and the administration record will carry forward.":"Choose the medication in your hand."}</p><div className="versed-medication-list">{visibleMedicationOptions.map(option=><button key={option.id} className={option.id==="fentanyl"&&medConfirmed?"selected":""} onClick={()=>{if(option.id==="fentanyl"){setAddingMedication(false);setMedConfirmed(true);resetDownstream();setStage("result")}else selectMedication(option.id,addingMedication?patientSnapshot:undefined)}}><b>{option.name}</b><span>{option.brand}</span><i>{option.id==="fentanyl"?"Select":"Open"}</i></button>)}</div></>}
        {stage==="concentration"&&<form className="builder-stage-form" onSubmit={event=>{event.preventDefault();if(labelConfirmed&&customConcentration){setConcentration(customConcentration);setStage("result")}}}><small className="eyebrow">CONCENTRATION</small><h1>Select the vial concentration</h1><p className="screen-help">Use the common concentration with one tap, or enter the physical label.</p><div className="builder-options concentration-options fentanyl-concentration-options"><button type="button" className={concentration===50&&labelConfirmed?"selected":""} onClick={()=>{setConcentration(50);setLabelConfirmed(true);resetDownstream();setStage("result")}}><b>50 mcg/mL</b><span>Common Fentanyl concentration</span></button><button type="button" className={concentration===0?"selected":""} onClick={()=>{setConcentration(0);setLabelConfirmed(false)}}><b>Custom label</b><span>Enter total drug and volume</span></button></div>{concentration===0&&<><div className="builder-custom"><label>Total drug<input inputMode="decimal" value={customAmount} onChange={event=>{setCustomAmount(event.target.value);setLabelConfirmed(false)}}/><b>mcg</b></label><label>Total volume<input inputMode="decimal" value={customVolume} onChange={event=>{setCustomVolume(event.target.value);setLabelConfirmed(false)}}/><b>mL</b></label>{customConcentration>0&&<strong>{fmt(customConcentration)} mcg/mL</strong>}</div><label className={labelConfirmed?"builder-confirm checked":"builder-confirm"}><input type="checkbox" disabled={!customConcentration} checked={labelConfirmed} onChange={event=>setLabelConfirmed(event.target.checked)}/><span><b>Custom concentration matches label</b>{customConcentration?`${customAmount} mcg in ${customVolume} mL`:"Enter both label values"}</span></label><button type="submit" className="continue" disabled={!labelConfirmed||!customConcentration}>Use custom concentration <span>→</span></button></>}</form>}
        {stage==="indication"&&<><small className="eyebrow">INDICATION</small><h1>Pain management</h1><p className="screen-help">Fentanyl has one released calculator indication during this pilot.</p><button className="builder-confirm checked auto-filled-field" onClick={()=>setStage("result")}><span><b>{indication}</b>Auto-filled from DMP 9230</span></button></>}
        {stage==="route"&&<><small className="eyebrow">ROUTE</small><h1>Select route</h1><p className="screen-help">Repeat timing and the cumulative maximum update automatically.</p><div className="builder-options route-options">{routes.map(option=><button key={option} className={route===option?"selected":""} onClick={()=>{setRoute(option);if(option==="IN"&&pediatric)setDoseRate(2);resetDownstream();setStage("result")}}><b>{option}</b><span>{option==="IN"?"10-minute repeat":"5-minute repeat"}</span></button>)}</div></>}
        {stage==="patient"&&<><small className="eyebrow">PATIENT</small><h1>Select patient and calculation weight</h1><p className="screen-help">Use quick choices whenever possible. Enter a number only when a better weight is known.</p><div className="builder-options fentanyl-patient-groups"><button className={patientGroup==="adult"?"selected":""} onClick={()=>choosePatient("adult")}><b>Adult</b><span>Estimated adult weight</span></button><button className={patientGroup==="older"?"selected":""} onClick={()=>choosePatient("older")}><b>Elderly / frail</b><span>Estimated adult weight</span></button><button className={patientGroup==="pediatric"?"selected":""} onClick={()=>choosePatient("pediatric")}><b>Pediatric 1–11</b><span>Age-based or measured estimate</span></button><button className={patientGroup==="infant"?"selected":""} onClick={()=>choosePatient("infant")}><b>Under 1 year</b><span>Length/age estimate • Base required</span></button></div>{patientGroup&&<WeightQuickSelect kind={pediatric?"pediatric":"adult"} valueKg={weightKg} onSelect={(kg,source)=>{const infantEstimate=source.includes("6–11 months")||source.includes("length-based"),nextPediatric=pediatric||source.includes("DMP age-band estimate")||infantEstimate,nextInfant=infantEstimate||patientGroup==="infant";if(pediatric&&infantEstimate){setPatientGroup("infant");setBaseConfirmed(false)}else if(patientGroup==="infant"&&source.includes("DMP age-band estimate")&&!source.includes("6–11 months")){setPatientGroup("pediatric");setBasePhysician("");setBaseConfirmed(false)}setWeightKg(kg);setWeightSource(source);resetDownstream();if(route==="IN"&&nextPediatric){setDoseRate(2);if(!nextInfant)setStage("result")}else if(!nextInfant)setStage("dose")}}/>}{weightKg>0&&infant&&<><div className="fentanyl-base-order"><small>DIRECT BASE AUTHORIZATION</small><label>Physician name<input value={basePhysician} onChange={event=>{setBasePhysician(event.target.value);setBaseConfirmed(false)}}/></label><label className={baseConfirmed?"builder-confirm checked":"builder-confirm"}><input type="checkbox" checked={baseConfirmed} onChange={event=>setBaseConfirmed(event.target.checked)}/><span><b>Direct verbal order received</b>Patient-specific Fentanyl dose authorized and will be documented</span></label></div><button className="continue" disabled={!patientComplete} onClick={()=>setStage("dose")}>Continue to dose <span>→</span></button></>}</>}
        {stage==="dose"&&<><small className="eyebrow">DOSE</small><h1>Select starting dose</h1><p className="screen-help">One tap selects the dose and returns to the calculation. Elderly or frail patients automatically receive one-half of the selected starting dose.</p><div className="dose-change-question"><span>Starting dose</span><div>{(route==="IN"&&pediatric?[2]:[1,2]).map(option=><button key={option} className={effectiveRate===option?"selected":""} onClick={()=>{setDoseRate(option);resetDownstream();setStage("result")}}>{option} mcg/kg{older?` → ${fmt(option/2)} mcg/kg`:""}</button>)}</div>{route==="IN"&&pediatric&&<small>Pediatric IN dosing is auto-filled at 2 mcg/kg.</small>}</div>{doseComplete&&<div className="live-math"><small>CALCULATED DOSE</small><b>{fmt(protocolDose)} mcg</b><span>{fmt(weightKg)} kg × {fmt(effectiveRate||0)} mcg/kg</span></div>}</>}
        {stage==="safety"&&<><small className="eyebrow">SAFETY</small><h1>Review all Fentanyl safety checks</h1><p className="screen-help">Read every item, then confirm the complete list with one tap.</p><div className="builder-safety-list">{safetyItems.map((item,index)=><div key={item}><b>{index+1}</b><span>{item}</span></div>)}</div><label className={safetyConfirmed?"builder-confirm checked":"builder-confirm"}><input type="checkbox" checked={safetyConfirmed} onChange={event=>setSafetyConfirmed(event.target.checked)}/><span><b>Confirm all safety checks</b>Every item above is confirmed</span></label><button className="continue" disabled={!safetyConfirmed} onClick={()=>setStage("result")}>Show final dose <span>→</span></button></>}
      </section>}
    </div>
  </main>;
}
