import {genericMedication,type GenericMedication,type GenericDosePath,type GenericDoseUnit} from "./dmpMedicationData";
import {DEFAULT_FIELD_MEDICATION_IDS} from "./medicationReleaseConfig";

const fixed=(amount:number,unit:GenericDoseUnit)=>({kind:"fixed" as const,amount,unit});
const kg=(amount:number,unit:GenericDoseUnit,min?:number,max?:number)=>({kind:"perKg" as const,amount,unit,min,max});
const range=(min:number,max:number,unit:GenericDoseUnit)=>({kind:"range" as const,min,max,unit});

const special:Record<string,GenericMedication>={
  adenosine:{id:"adenosine",name:"Adenosine",protocolId:"9010",page:123,contraindications:["Irregular tachycardia","Heart transplant history","Bronchospasm/asthma precaution reviewed"],paths:[
    {id:"adult-svt",label:"Regular narrow-complex AV nodal reentrant tachycardia — adult",agent:"Adenosine",patient:"adult",route:"IV",formula:fixed(12,"mg"),repeat:"One additional 12 mg rapid IV dose; contact medical control for further considerations.",administration:"Rapid IV bolus followed immediately by a normal saline flush. Continuous ECG monitoring required.",protocol:"Tachyarrhythmia with Poor Perfusion",volumeRequired:true,maxAdministrations:2},
    {id:"ped-svt",label:"Regular narrow-complex AV nodal reentrant tachycardia — pediatric",agent:"Adenosine",patient:"pediatric",route:"IV",formula:kg(.1,"mg",undefined,6),repeat:"Under direct Base order, one additional 0.2 mg/kg rapid IV dose may be given, maximum 12 mg.",administration:"Rapid IV bolus followed immediately by a normal saline flush. Continuous ECG monitoring required.",protocol:"Tachyarrhythmia with Poor Perfusion",volumeRequired:true,baseContact:"Direct Base order required for pediatric Adenosine.",linkedDose:{perKg:.2,unit:"mg",afterMinutes:0,max:12,label:"Additional pediatric dose",administration:"Rapid IV bolus followed immediately by normal saline flush."}},
  ]},
  albuterol:{id:"albuterol",name:"Albuterol",protocolId:"9020",page:125,contraindications:["Severe tachycardia considered as a relative contraindication"],paths:[
    {id:"allergy",label:"Wheezing associated with allergic reaction",agent:"Albuterol",patient:"all",route:"Nebulized",formula:fixed(2.5,"mg"),repeat:"May repeat twice for a total of 3 single doses.",administration:"Nebulize 2.5 mg in 3 mL at 6–8 L/min over 5–15 minutes. IM Epinephrine is first-line when wheezing is associated with anaphylaxis.",protocol:"Allergy and Anaphylaxis",volumeRequired:false,repeatAfterMinutes:5,maxAdministrations:3},
    {id:"bronchospasm",label:"Bronchospasm — single nebulizer dose",agent:"Albuterol",patient:"all",route:"Nebulized",formula:fixed(2.5,"mg"),repeat:"May repeat twice for a total of 3 single doses.",administration:"Nebulize 2.5 mg in 3 mL at 6–8 L/min over 5–15 minutes.",protocol:"Adult/Pediatric Wheezing",repeatAfterMinutes:5,maxAdministrations:3},
    {id:"continuous",label:"Severe bronchospasm — continuous nebulizer dose",agent:"Albuterol",patient:"all",route:"Nebulized",formula:fixed(7.5,"mg"),repeat:"Continuous nebulizer dose uses three 2.5 mg/3 mL containers.",administration:"Nebulize 7.5 mg in 9 mL at 6–8 L/min.",protocol:"Adult/Pediatric Wheezing"},
    {id:"hyperkalemia",label:"Hyperkalemia or crush injury — continuous nebulizer dose",agent:"Albuterol",patient:"all",route:"Nebulized",formula:fixed(7.5,"mg"),repeat:"Single continuous treatment per pathway.",administration:"Nebulize 7.5 mg in 9 mL at 6–8 L/min.",protocol:"Hyperkalemia"},
  ]},
  diphenhydramine:{id:"diphenhydramine",name:"Diphenhydramine",protocolId:"9100",page:144,contraindications:["Narrow-angle glaucoma precaution","Asthma/COPD secretion-thickening precaution","Additive CNS-depressant effects reviewed"],paths:[
    {id:"adult-allergy",label:"Allergic reaction — adult",agent:"Diphenhydramine",patient:"adult",route:"IV/IO/IM",formula:fixed(50,"mg"),repeat:"No routine repeat dose is listed in DMP 9100.",administration:"Slow IV/IO/IM. For mild reactions, consider PO administration per protocol.",protocol:"Allergy and Anaphylaxis",volumeRequired:true},
    {id:"ped-allergy",label:"Allergic reaction — pediatric",agent:"Diphenhydramine",patient:"pediatric",route:"IV/IO/IM",formula:kg(1,"mg",undefined,50),repeat:"No routine repeat dose is listed in DMP 9100.",administration:"Slow IV/IO/IM; maximum 50 mg.",protocol:"Allergy and Anaphylaxis",volumeRequired:true},
    {id:"adult-dystonic",label:"Dystonic medication reaction or akathisia — adult",agent:"Diphenhydramine",patient:"adult",route:"IV/IO/IM",formula:fixed(50,"mg"),repeat:"No routine repeat dose is listed in DMP 9100.",administration:"Slow IV/IO/IM.",protocol:"Diphenhydramine",volumeRequired:true},
    {id:"ped-dystonic",label:"Dystonic medication reaction or akathisia — pediatric",agent:"Diphenhydramine",patient:"pediatric",route:"IV/IO/IM",formula:kg(1,"mg",undefined,50),repeat:"No routine repeat dose is listed in DMP 9100.",administration:"Slow IV/IO/IM; maximum 50 mg.",protocol:"Diphenhydramine",volumeRequired:true},
  ]},
  methylprednisolone:{id:"methylprednisolone",name:"Methylprednisolone",protocolId:"9200",page:158,contraindications:["Active gastrointestinal bleeding precaution"],paths:[
    {id:"adult-allergy",label:"Allergic reaction / anaphylaxis — adult",agent:"Methylprednisolone",patient:"adult",route:"IV/IO",formula:fixed(125,"mg"),repeat:"No routine repeat dose is listed in DMP 9200.",administration:"Slow IV/IO bolus over 2 minutes. Reconstitute and use immediately.",protocol:"Allergy and Anaphylaxis",volumeRequired:true},
    {id:"ped-allergy",label:"Allergic reaction / anaphylaxis — pediatric",agent:"Methylprednisolone",patient:"pediatric",route:"IV/IO",formula:kg(2,"mg",undefined,125),repeat:"No routine repeat dose is listed in DMP 9200.",administration:"Slow IV/IO bolus over 2 minutes; maximum 125 mg.",protocol:"Allergy and Anaphylaxis",volumeRequired:true},
    {id:"adult-airway",label:"Severe asthma or COPD — adult",agent:"Methylprednisolone",patient:"adult",route:"IV/IO",formula:fixed(125,"mg"),repeat:"No routine repeat dose is listed in DMP 9200.",administration:"Slow IV/IO bolus over 2 minutes. Do not delay transport or primary airway/ventilation treatment.",protocol:"Adult/Pediatric Wheezing",volumeRequired:true},
    {id:"ped-airway",label:"Severe asthma — pediatric",agent:"Methylprednisolone",patient:"pediatric",route:"IV/IO",formula:kg(2,"mg",undefined,125),repeat:"No routine repeat dose is listed in DMP 9200.",administration:"Slow IV/IO bolus over 2 minutes; maximum 125 mg.",protocol:"Adult/Pediatric Wheezing",volumeRequired:true},
    {id:"addisonian",label:"Suspected Addisonian crisis",agent:"Methylprednisolone",patient:"all",route:"IV/IO",formula:fixed(125,"mg"),repeat:"No routine repeat dose is listed in DMP 9200.",administration:"Slow IV/IO bolus over 2 minutes.",protocol:"Adrenal Insufficiency",volumeRequired:true},
  ]},
  magnesium:{id:"magnesium",name:"Magnesium Sulfate",protocolId:"9190",page:157,contraindications:["Confirm route and infusion/push timing for the selected indication"],paths:[
    {id:"torsades-stable",label:"Torsades — stable/intermittent",agent:"Magnesium Sulfate",patient:"adult",route:"IV/IO",formula:fixed(2000,"mg"),repeat:"No repeat dose is listed in DMP 9190.",administration:"IV/IO drip — not push. Dilute in 50 mL normal saline and infuse over 15 minutes.",protocol:"Tachyarrhythmia with Poor Perfusion",volumeRequired:true},
    {id:"torsades-unstable",label:"Torsades — unstable/peri-arrest",agent:"Magnesium Sulfate",patient:"adult",route:"IV",formula:fixed(2000,"mg"),repeat:"No repeat dose is listed in DMP 9190.",administration:"Administer undiluted by IV push over 2 minutes.",protocol:"Tachyarrhythmia with Poor Perfusion",volumeRequired:true},
    {id:"torsades-arrest-adult",label:"Torsades — cardiac arrest — adult",agent:"Magnesium Sulfate",patient:"adult",route:"IV/IO",formula:fixed(2000,"mg"),repeat:"No repeat dose is listed in DMP 9190.",administration:"Administer undiluted by IV/IO push during cardiac arrest.",protocol:"Medical Pulseless Arrest",volumeRequired:true},
    {id:"torsades-arrest-ped",label:"Torsades — cardiac arrest — pediatric",agent:"Magnesium Sulfate",patient:"pediatric",route:"IV/IO",formula:kg(25,"mg",undefined,2000),repeat:"No repeat dose is listed in DMP 9190.",administration:"Administer undiluted by IV/IO push during cardiac arrest; maximum 2 g.",protocol:"Medical Pulseless Arrest",volumeRequired:true},
    {id:"bronchospasm-adult",label:"Refractory severe bronchospasm — adult",agent:"Magnesium Sulfate",patient:"adult",route:"IV",formula:fixed(2000,"mg"),repeat:"No repeat dose is listed in DMP 9190.",administration:"IV drip — not push. Dilute in 50 mL normal saline and infuse over 15 minutes.",protocol:"Adult/Pediatric Wheezing",volumeRequired:true},
    {id:"bronchospasm-ped",label:"Refractory severe bronchospasm — pediatric",agent:"Magnesium Sulfate",patient:"pediatric",route:"IV",formula:kg(50,"mg",undefined,2000),repeat:"No repeat dose is listed in DMP 9190.",administration:"IV drip — not push. Dilute and administer over 30 minutes; maximum 2 g.",protocol:"Adult/Pediatric Wheezing",volumeRequired:true},
    {id:"eclampsia-iv",label:"Eclampsia — IV/IO",agent:"Magnesium Sulfate",patient:"adult",route:"IV/IO",formula:fixed(6000,"mg"),repeat:"No repeat dose is listed in DMP 9190.",administration:"IV/IO drip — not push. Dilute in 50 mL normal saline and infuse over 15 minutes.",protocol:"Obstetrical Complications",volumeRequired:true},
    {id:"eclampsia-im",label:"Eclampsia — IM",agent:"Magnesium Sulfate",patient:"adult",route:"IM",formula:fixed(10000,"mg"),repeat:"No repeat dose is listed in DMP 9190.",administration:"Give 5 g in each buttock. Maximum volume per site is 10 mL.",protocol:"Obstetrical Complications",volumeRequired:true},
  ]},
  fentanyl:{id:"fentanyl",name:"Fentanyl",protocolId:"9230",page:163,contraindications:["Hemodynamic instability or shock","Respiratory depression","Opioid + benzodiazepine coadministration requires direct physician verbal order"],paths:[
    {id:"adult-ivio",label:"Moderate to severe pain — adult IV/IO",agent:"Fentanyl",patient:"adult",route:"IV/IO",formula:kg(2,"mcg"),repeat:"Reassess after 5 minutes. Maximum cumulative 3 mcg/kg.",administration:"Administer slowly and titrate to tolerable pain.",protocol:"Pain Management",volumeRequired:true,repeatAfterMinutes:5,maxCumulativePerKg:3},
    {id:"adult-im",label:"Moderate to severe pain — adult IM",agent:"Fentanyl",patient:"adult",route:"IM",formula:kg(2,"mcg"),repeat:"Reassess after 5 minutes. Maximum cumulative 3 mcg/kg.",administration:"Administer IM; IV is preferred for accurate titration.",protocol:"Pain Management",volumeRequired:true,repeatAfterMinutes:5,maxCumulativePerKg:3},
    {id:"adult-in",label:"Moderate to severe pain — adult IN",agent:"Fentanyl",patient:"adult",route:"IN",formula:kg(2,"mcg"),repeat:"Reassess after 10 minutes. Maximum cumulative 4 mcg/kg.",administration:"Divide equally between nostrils; maximum 1 mL per nostril.",protocol:"Pain Management",volumeRequired:true,repeatAfterMinutes:10,maxCumulativePerKg:4},
    {id:"ped-ivio",label:"Moderate to severe pain — pediatric IV/IO",agent:"Fentanyl",patient:"pediatric",route:"IV/IO",formula:kg(1,"mcg"),repeat:"Reassess after 5 minutes. Maximum cumulative 3 mcg/kg.",administration:"Administer slowly and titrate to tolerable pain.",protocol:"Pain Management",volumeRequired:true,repeatAfterMinutes:5,maxCumulativePerKg:3},
    {id:"ped-im",label:"Moderate to severe pain — pediatric IM",agent:"Fentanyl",patient:"pediatric",route:"IM",formula:kg(1,"mcg"),repeat:"Reassess after 5 minutes. Maximum cumulative 3 mcg/kg.",administration:"Administer IM; IV is preferred for accurate titration.",protocol:"Pain Management",volumeRequired:true,repeatAfterMinutes:5,maxCumulativePerKg:3},
    {id:"ped-in",label:"Moderate to severe pain — pediatric IN",agent:"Fentanyl",patient:"pediatric",route:"IN",formula:kg(2,"mcg"),repeat:"Reassess after 10 minutes. Maximum cumulative 4 mcg/kg.",administration:"Divide equally between nostrils; maximum 1 mL per nostril.",protocol:"Pain Management",volumeRequired:true,repeatAfterMinutes:10,maxCumulativePerKg:4},
  ]},
  midazolam:{id:"midazolam",name:"Midazolam (Versed)",protocolId:"9070",page:136,contraindications:["Hypotension","Respiratory depression","Opioid coadministration requires direct physician verbal order"],paths:[
    {id:"adult-seizure-iv",label:"Status epilepticus — adult IV/IO",agent:"Midazolam",patient:"adult",route:"IV/IO",formula:fixed(5,"mg"),repeat:"May repeat once after 5 minutes; Base contact for more than 2 doses.",administration:"Administer IV/IO with continuous ventilation monitoring.",protocol:"Seizure",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"adult-seizure-inim",label:"Status epilepticus — adult IM/IN",agent:"Midazolam",patient:"adult",route:"IM/IN",formula:fixed(10,"mg"),repeat:"May repeat once after 5 minutes; Base contact for more than 2 doses.",administration:"IN is preferred over IM when no IV can be rapidly obtained.",protocol:"Seizure",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"ped-seizure-iv",label:"Status epilepticus — pediatric IV/IO",agent:"Midazolam",patient:"pediatric",route:"IV/IO",formula:kg(.1,"mg",undefined,5),repeat:"May repeat once after 5 minutes; Base contact for more than 2 doses.",administration:"Administer IV/IO with continuous ventilation monitoring.",protocol:"Seizure",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"ped-seizure-inim",label:"Status epilepticus — pediatric IM/IN",agent:"Midazolam",patient:"pediatric",route:"IM/IN",formula:kg(.2,"mg",undefined,10),repeat:"May repeat once after 5 minutes; Base contact for more than 2 doses.",administration:"IN is preferred over IM when no IV can be rapidly obtained.",protocol:"Seizure",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"adult-cardiovert",label:"Sedation for cardioversion — adult",agent:"Midazolam",patient:"adult",route:"IV/IO",formula:fixed(2,"mg"),repeat:"May repeat once after 5 minutes; Base contact for more than 2 doses.",administration:"Continuous ECG, SpO₂ and ventilation monitoring.",protocol:"Synchronized Cardioversion",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"adult-pacing",label:"Sedation for transcutaneous pacing — adult",agent:"Midazolam",patient:"adult",route:"IV/IO",formula:fixed(2,"mg"),repeat:"May repeat once after 5 minutes; Base contact for more than 2 doses.",administration:"Continuous ECG, SpO₂ and ventilation monitoring.",protocol:"Transcutaneous Cardiac Pacing",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:2},
    {id:"adult-agitation",label:"Agitated/combative patient — adult IMC-RASS +3/+4",agent:"Midazolam",patient:"adult",route:"IV/IO/IM",formula:fixed(5,"mg"),repeat:"If still IMC-RASS +3/+4 after 5 minutes, switch to an antipsychotic. Additional sedation requires Base.",administration:"Apply cardiac, SpO₂ and ventilation monitoring; waveform capnography is recommended.",protocol:"Agitated/Combative Patient",volumeRequired:true},
    {id:"adult-imminent",label:"Imminent risk of bodily harm — adult IMC-RASS +4",agent:"Midazolam",patient:"adult",route:"IM",formula:fixed(10,"mg"),repeat:"Contact Base for additional sedation orders.",administration:"IM route only. Continuous airway and ventilation monitoring.",protocol:"Agitated/Combative Patient",volumeRequired:true},
  ]},
  ketamine:{id:"ketamine",name:"Ketamine",protocolId:"500:62",page:1,contraindications:["Pediatric patient","Penetrating eye trauma"],paths:[
    {id:"adult-analgesia",label:"Moderate to severe pain — adult analgesia waiver",agent:"Ketamine",patient:"adult",route:"IV/IO drip",formula:kg(.25,"mg"),repeat:"One standing-order repeat after reassessment; Base contact for subsequent doses.",administration:"IV/IO drip/infusion: mix in 50–100 mL NS and administer over 5–10 minutes when conditions allow. Slow IV push may be used when mixing is not possible but may cause more dysphoria.",protocol:"Ketamine Waiver: Analgesia",volumeRequired:true,maxAdministrations:2,monitoring:["Continuous cardiac monitoring","Pulse oximetry","Continuous waveform capnography","BVM ventilation and suction immediately available"]},
  ]},
  epinephrine:{id:"epinephrine",name:"Epinephrine",protocolId:"9120",page:148,contraindications:["Confirm the selected route and physical concentration match the intended Epinephrine pathway","Dosing error risk reviewed"],paths:[
    {id:"arrest-adult",label:"Pulseless arrest — adult",agent:"Epinephrine",patient:"adult",route:"IV/IO",formula:fixed(1,"mg"),repeat:"Repeat every 3–5 minutes; maximum 3 doses. Additional dose only for recurrent arrest after ROSC or narrow-complex PEA.",administration:"IV/IO bolus. Use the department-approved 0.1 mg/mL arrest formulation.",protocol:"Medical Pulseless Arrest",volumeRequired:true,repeatAfterMinutes:3,maxAdministrations:3,suggestedConcentration:.1},
    {id:"arrest-ped",label:"Pulseless arrest — pediatric",agent:"Epinephrine",patient:"pediatric",route:"IV/IO",formula:kg(.01,"mg"),repeat:"Repeat every 3–5 minutes. DMP 9120 does not state a pediatric dose-count maximum.",administration:"IV/IO bolus. Use the department-approved 0.1 mg/mL arrest formulation.",protocol:"Medical Pulseless Arrest",volumeRequired:true,repeatAfterMinutes:3,openEndedRepeats:true,suggestedConcentration:.1},
    {id:"allergy-adult",label:"Systemic allergic reaction — adult IM",agent:"Epinephrine",patient:"adult",route:"IM",formula:fixed(.5,"mg"),repeat:"May repeat once.",administration:"IM in the lateral thigh. Use 1 mg/mL formulation.",protocol:"Allergy and Anaphylaxis",volumeRequired:true,maxAdministrations:2,suggestedConcentration:1},
    {id:"allergy-ped-small",label:"Systemic allergic reaction — pediatric under 25 kg IM",agent:"Epinephrine",patient:"pediatric",route:"IM",formula:fixed(.15,"mg"),repeat:"May repeat twice every 5 minutes.",administration:"IM in the lateral thigh. Use 1 mg/mL formulation.",protocol:"Allergy and Anaphylaxis",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:3,suggestedConcentration:1,requiresWeight:true},
    {id:"allergy-ped-large",label:"Systemic allergic reaction — pediatric 25 kg or greater IM",agent:"Epinephrine",patient:"pediatric",route:"IM",formula:fixed(.3,"mg"),repeat:"May repeat twice every 5 minutes.",administration:"IM in the lateral thigh. Use 1 mg/mL formulation.",protocol:"Allergy and Anaphylaxis",volumeRequired:true,repeatAfterMinutes:5,maxAdministrations:3,suggestedConcentration:1,requiresWeight:true},
    {id:"push-dose",label:"Hypotension or refractory anaphylaxis — adult push dose",agent:"Epinephrine",patient:"adult",route:"IV/IO",formula:range(.01,.02,"mg"),repeat:"Give 0.01–0.02 mg aliquots every 1–5 minutes as needed. DMP 9120 does not state a dose-count maximum.",administration:"IV push-dose. Follow department-approved mixing guidance and verify the prepared concentration before use.",protocol:"Medical Shock",volumeRequired:true,repeatAfterMinutes:1,openEndedRepeats:true},
    {id:"infusion",label:"Hypotension or refractory anaphylaxis — adult infusion",agent:"Epinephrine",patient:"adult",route:"IV/IO infusion",formula:range(.002,.01,"mg"),repeat:"Titrate to SBP >90 mmHg, improved respiratory status and improved perfusion/mentation.",administration:"IV/IO infusion — not push. Follow department-approved bag preparation and titration guidance.",protocol:"Medical Shock",volumeRequired:true,openEndedRepeats:true},
    {id:"brady-ped",label:"Bradycardia with poor perfusion — pediatric",agent:"Epinephrine",patient:"pediatric",route:"IV/IO",formula:kg(.01,"mg"),repeat:"No routine repeat is listed in DMP 9120 for this indication.",administration:"Pediatric IV/IO dose. Use the department-approved 0.1 mg/mL formulation.",protocol:"Bradyarrhythmia with Poor Perfusion",volumeRequired:true,suggestedConcentration:.1},
    {id:"stridor",label:"Stridor at rest — alternative to racemic epinephrine",agent:"Epinephrine",patient:"pediatric",route:"Nebulized",formula:fixed(5,"mg"),repeat:"One nebulized dose; pediatric repeat requires Base contact.",administration:"Nebulized — not injected. Give 5 mL of 1 mg/mL solution.",protocol:"Pediatric Stridor/Croup",volumeRequired:true,suggestedConcentration:1},
  ]},
};

function filtered(base:GenericMedication,id:string,name:string,agent:string):GenericMedication{
  return {...base,id,name,paths:base.paths.filter(path=>path.agent.toLowerCase()===agent.toLowerCase())};
}

export function fieldMedicationDefinition(id:string):GenericMedication|null{
  if(special[id])return special[id];
  const direct=genericMedication(id);
  if(direct)return direct;
  if(id==="ondansetron"){
    const base=genericMedication("antiemetics");
    return base?filtered(base,id,"Ondansetron","Ondansetron"):null;
  }
  if(id==="haloperidol"){
    const base=genericMedication("antipsychotics");
    return base?filtered(base,id,"Haloperidol","Haloperidol"):null;
  }
  return null;
}

export function assertReleasedMedicationDefinitions(){
  const missing=DEFAULT_FIELD_MEDICATION_IDS.filter(id=>!fieldMedicationDefinition(id));
  if(missing.length)throw new Error(`One-engine medication definitions missing: ${missing.join(", ")}`);
  return true;
}

export const releasedFieldMedicationDefinitions=DEFAULT_FIELD_MEDICATION_IDS.map(id=>fieldMedicationDefinition(id)!).filter(Boolean);
