import {useEffect,useState} from "react";
import type {GenericTreatmentContext} from "./DmpMedicationCalculator";
import CalculationBoard,{type CalculationBox} from "./CalculationBoard";
import WeightQuickSelect from "./WeightQuickSelect";
import DoseSyringe from "./DoseSyringe";
import type {EncounterPatient} from "./VersedBuilder";
import "./versedBuilder.css";
import "./versedForm.css";
import "./versedConsole.css";

type RecordedAdministration={drug:string;reason:string;route:string;dose:number;unit:string;volume:number;time:number;concentration:string;patient?:string};
type MedicationOption={id:string;name:string;brand:string;released:boolean};
type Props={close:()=>void;record:(entry:RecordedAdministration)=>void;onContextChange:(context:GenericTreatmentContext|null)=>void;medicationOptions:MedicationOption[];selectMedication:(id:string,patient?:EncounterPatient)=>void;initialPatient?:EncounterPatient|null};
type Stage="medication"|"concentration"|"indication"|"route"|"patient"|"dose"|"safety"|"result";
type Administration={dose:number;volume:number;time:number};

const indication="Moderate to severe pain in an adult";
const route="IV/IO";
const doseRate=.25;
const fmt=(value:number)=>Number.isFinite(value)?Number(value.toFixed(Math.abs(value)<1?2:1)).toString():"—";
const safetyItems=[
  "The patient is an adult with moderate to severe pain.",
  "No penetrating eye trauma is present.",
  "IV or IO access is established.",
  "Cardiac monitoring, pulse oximetry and continuous waveform capnography are in place.",
  "Bag-valve-mask ventilation and suction are immediately available.",
  "The dose will be mixed in 50–100 mL NS and administered over 5–10 minutes when conditions allow.",
];

export default function KetamineBuilder({close,record,onContextChange,medicationOptions,selectMedication,initialPatient}:Props){
  const [stage,setStage]=useState<Stage>("result"),[concentration,setConcentration]=useState<number|null>(null),[customAmount,setCustomAmount]=useState(""),[customVolume,setCustomVolume]=useState(""),[labelConfirmed,setLabelConfirmed]=useState(false),[weightKg,setWeightKg]=useState(initialPatient?.patient==="adult"&&initialPatient.weightKg?initialPatient.weightKg:0),[weightSource,setWeightSource]=useState(initialPatient?.patient==="adult"&&initialPatient.weightKg?"carried from current patient":""),[plannedDose,setPlannedDose]=useState(""),[safetyConfirmed,setSafetyConfirmed]=useState(false),[administrations,setAdministrations]=useState<Administration[]>([]),[addingMedication,setAddingMedication]=useState(false),[bagVolume,setBagVolume]=useState<50|100>(50),[infusionMinutes,setInfusionMinutes]=useState<5|10>(10),[dropFactor,setDropFactor]=useState<60|10|15>(60);
  const customConcentration=Number(customAmount)>0&&Number(customVolume)>0?Number(customAmount)/Number(customVolume):0;
  const protocolDose=weightKg>0?weightKg*doseRate:0,selectedDose=Number(plannedDose),selectedDoseValid=selectedDose>0&&selectedDose<=protocolDose,volume=concentration&&selectedDoseValid?selectedDose/concentration:0;
  const patientComplete=weightKg>0,doseComplete=protocolDose>0&&selectedDoseValid,recorded=administrations.length>0,repeatAvailable=administrations.length===1;
  const dosePreviewReady=!!concentration&&labelConfirmed&&patientComplete&&doseComplete&&administrations.length<2;
  const calculationReady=!!concentration&&labelConfirmed&&patientComplete&&doseComplete&&safetyConfirmed&&administrations.length<2;
  const patientLabel=weightKg?`Adult • ${fmt(weightKg*2.20462)} lb (${fmt(weightKg)} kg)${weightSource?` • ${weightSource}`:""}`:"";
  const pumpRate=bagVolume*60/infusionMinutes,gravityRate=Math.round(bagVolume*dropFactor/infusionMinutes);
  const patientSnapshot:EncounterPatient|undefined=weightKg?{patient:"adult",weightKg}:undefined;
  const visibleMedicationOptions=medicationOptions.filter(option=>option.released);
  const medicationReference=<aside className="versed-medication-reference ketamine-medication-reference" aria-label="Selected Ketamine reference"><div className="versed-reference-vial ketamine-reference-vial"><small>KETAMINE</small><b>Rx</b><span>200 mg / 20 mL</span></div><span><small>SELECTED MEDICATION</small><b>Ketamine</b><em>Analgesia waiver • adult IV/IO</em></span></aside>;

  useEffect(()=>{if(protocolDose>0)setPlannedDose(fmt(protocolDose))},[protocolDose]);
  useEffect(()=>{onContextChange({medication:"Ketamine",indication,route,dose:protocolDose?`${fmt(protocolDose)} mg`:"Pending adult weight",volume:volume?`${fmt(volume)} mL`:"Pending calculated dose",administration:"Mix in 50–100 mL NS and administer over 5–10 minutes. Slow IV push is permitted when mixing is not possible but may cause more dysphoria.",repeat:"One repeat dose is a standing order. The waiver does not specify a minimum repeat interval. Base contact is required for subsequent doses.",monitoring:["Continuous cardiac monitoring, pulse oximetry and waveform capnography.","Have BVM ventilation and suction ready; watch for laryngospasm, dysphoria, nausea/vomiting and hypersalivation."],protocolId:"500:62",protocolName:"Ketamine Waiver: Analgesia",protocolPage:1});return()=>onContextChange(null)},[protocolDose,volume,onContextChange]);

  const giveNow=()=>{if(!calculationReady||!concentration)return;const time=Date.now(),givenVolume=selectedDose/concentration;record({drug:"Ketamine",reason:indication,route,dose:selectedDose,unit:"mg",volume:givenVolume,time,concentration:`${fmt(concentration)} mg/mL`,patient:patientLabel});setAdministrations(items=>[...items,{dose:selectedDose,volume:givenVolume,time}])};
  const finishConcentration=(value:number)=>{setConcentration(value);setLabelConfirmed(true);setSafetyConfirmed(false);setStage(patientComplete?"result":"patient")};
  const board:CalculationBox[]=[
    {id:"concentration",label:"CONCENTRATION",value:concentration?`${fmt(concentration)} mg/mL`:"",detail:labelConfirmed?"Physical label confirmed":"Confirm physical label",complete:!!concentration&&labelConfirmed,active:stage==="concentration",available:!recorded,onClick:()=>!recorded&&setStage("concentration")},
    {id:"indication",label:"INDICATION",value:indication,detail:"Adult analgesia auto-filled",complete:true,notRequired:true,active:stage==="indication",available:!recorded,onClick:()=>!recorded&&setStage("indication")},
    {id:"route",label:"ROUTE",value:route,detail:"Waiver route auto-filled",complete:true,notRequired:true,active:stage==="route",available:!recorded,onClick:()=>!recorded&&setStage("route")},
    {id:"patient",label:"PATIENT",value:patientLabel,detail:patientComplete?"Adult calculation weight selected":"Select estimated adult weight",complete:patientComplete,active:stage==="patient",available:!recorded,onClick:()=>!recorded&&setStage("patient")},
    {id:"dose",label:"DOSE",value:doseComplete?`${fmt(selectedDose)} mg`:protocolDose?`${fmt(protocolDose)} mg`:"",detail:doseComplete&&selectedDose<protocolDose?"Lesser dose selected":"0.25 mg/kg",complete:doseComplete,active:stage==="dose",available:!recorded&&patientComplete,onClick:()=>!recorded&&setStage("dose")},
    {id:"safety",label:"SAFETY",value:"All checks confirmed",detail:safetyConfirmed?"One confirmation":"Review complete safety list",complete:safetyConfirmed,active:stage==="safety",available:!recorded,onClick:()=>!recorded&&setStage("safety")},
  ];

  return <main className="versed-builder ketamine-builder">
    <div className="versed-builder-top"><button className="drug-back-button" onClick={close}>‹ Back to medications</button><span>KETAMINE WORKING MED</span><button onClick={close}>Start over</button></div>
    <div className={`versed-layout${calculationReady?" calculation-complete":""}`}>
      <header className="builder-medication-banner">{medicationReference}</header>
      <aside className="versed-left-column" aria-label="Calculation controls"><CalculationBoard boxes={board} className="versed-status-board"/><div id="versed-left-tools" className="versed-left-tools"/></aside>
      {stage==="result"&&<section className="versed-dashboard" aria-label="Ketamine dose and repeat information">
        <header className="administration-area-heading"><small>DRUG ADMINISTRATION</small><b>Ketamine</b><span>IV/IO • 50–100 mL NS over 5–10 minutes</span></header>
        <section className={calculationReady?"dashboard-primary-dose ready":"dashboard-primary-dose pending"}><small>DOSE AND AMOUNT TO GIVE</small>{dosePreviewReady?<><div className="dashboard-dose-answer"><strong>{fmt(selectedDose)} mg</strong><span>Draw <b>{volume?`${fmt(volume)} mL`:"—"}</b></span></div><p>0.25 mg/kg • mix in 50–100 mL NS • administer over 5–10 minutes</p></>:<strong className="dashboard-dose-pending">Complete required checks</strong>}</section>
        {dosePreviewReady&&<DoseSyringe volume={volume}/>}
        {dosePreviewReady&&<section className="administration-special ketamine-setup"><small>SETUP AND INFUSION RATE</small><div className="setup-picks"><span><b>Final NS volume</b><i>{[50,100].map(size=><button key={size} className={bagVolume===size?"selected":""} onClick={()=>setBagVolume(size as 50|100)}>{size} mL</button>)}</i></span><span><b>Infusion time</b><i>{[5,10].map(minutes=><button key={minutes} className={infusionMinutes===minutes?"selected":""} onClick={()=>setInfusionMinutes(minutes as 5|10)}>{minutes} min</button>)}</i></span><span><b>Tubing drop factor</b><i>{([60,10,15] as const).map(factor=><button key={factor} className={dropFactor===factor?"selected":""} onClick={()=>setDropFactor(factor)}>{factor} gtt/mL</button>)}</i></span></div><div><span><b>Prepare</b>Draw {fmt(volume)} mL Ketamine. Withdraw {fmt(volume)} mL from the NS bag, then add the medication to maintain a final volume of {bagVolume} mL.</span><span><b>Pump rate</b>{fmt(pumpRate)} mL/hr for {infusionMinutes} minutes</span><span><b>Gravity rate</b>{gravityRate} drops/min • {dropFactor} gtt/mL tubing</span><span className="wide"><b>Special instructions</b>Use an infusion pump when available. If time and conditions do not allow mixing, the waiver permits slow IV push but warns it may cause more dysphoria.</span></div></section>}
        {!calculationReady&&administrations.length<2&&<button className="dashboard-required" onClick={()=>setStage(board.find(item=>!item.complete)?.id as Stage||"concentration")}><b>Choose the next red box</b><span>Complete the required information.</span><i>Open ›</i></button>}
        <button className={recorded?"dashboard-give-now repeat":"dashboard-give-now"} disabled={!calculationReady} onClick={giveNow}><small>{recorded?"GIVE REPEAT DOSE NOW":"GIVE NOW"}</small><strong>{selectedDoseValid?`${fmt(selectedDose)} mg • ${fmt(volume)} mL`:"Complete dose"}</strong><span>IV/IO • records this administration</span></button>
        <section className={`dashboard-timer repeat-status ${administrations.length>=2?"unavailable":""}`}>{administrations.length===0?<><small>REPEAT DOSE</small><strong>1 REPEAT</strong><span>Standing order after reassessment; no minimum interval is stated in waiver 500:62</span></>:repeatAvailable?<><small>REPEAT DOSE</small><strong>AVAILABLE</strong><span>Reassess first. Base contact is required after this repeat dose.</span><b className="next-dose-field">Up to {fmt(selectedDose)} mg • {fmt(volume)} mL</b></>:<><small>NO FURTHER STANDING-ORDER DOSE</small><strong>BASE</strong><span>Base contact is required for subsequent Ketamine doses</span></>}</section>
        {recorded&&<div className="dashboard-recorded"><b>✓ {administrations.length} dose{administrations.length===1?"":"s"} recorded</b><span>{administrations.map(item=>`${fmt(item.dose)} mg`).join(" + ")}</span></div>}
        {recorded&&<button className="dashboard-add-med" onClick={()=>{setAddingMedication(true);setStage("medication")}}>+ Additional medication • same patient</button>}
      </section>}
      {stage!=="result"&&<section className="builder-workspace versed-inline-workspace" aria-label={`Edit ${stage}`}><button className="versed-inline-close" onClick={()=>setStage("result")} aria-label="Close popup">×</button>
        {stage==="medication"&&<><h1>Add medication</h1><p className="screen-help">Patient weight carries forward.</p><div className="versed-medication-list">{visibleMedicationOptions.map(option=><button key={option.id} className={option.id==="ketamine"?"selected":""} onClick={()=>option.id==="ketamine"?setStage("result"):selectMedication(option.id,addingMedication?patientSnapshot:undefined)}><b>{option.name}</b><span>{option.brand}</span><i>{option.id==="ketamine"?"Current":"Open"}</i></button>)}</div></>}
        {stage==="concentration"&&<form onSubmit={event=>{event.preventDefault();if(labelConfirmed&&(concentration||customConcentration)){if(concentration===0)finishConcentration(customConcentration)}}}><h1>Select vial concentration</h1><p className="screen-help">The waiver lists 200 mg/20 mL but warns that Ketamine is stocked in different concentrations. Confirm the physical vial.</p><div className="builder-options concentration-options"><button type="button" className={concentration===10&&labelConfirmed?"selected":""} onClick={()=>{finishConcentration(10)}}><b>200 mg / 20 mL</b><span>10 mg/mL waiver stock</span></button><button type="button" className={concentration===0?"selected":""} onClick={()=>{setConcentration(0);setLabelConfirmed(false)}}><b>Custom label</b><span>Enter total drug and volume</span></button></div>{concentration===0&&<><div className="builder-custom"><label>Total drug<input inputMode="decimal" value={customAmount} onChange={event=>{setCustomAmount(event.target.value);setLabelConfirmed(false)}}/><b>mg</b></label><label>Total volume<input inputMode="decimal" value={customVolume} onChange={event=>{setCustomVolume(event.target.value);setLabelConfirmed(false)}}/><b>mL</b></label>{customConcentration>0&&<strong>{fmt(customConcentration)} mg/mL</strong>}</div><label className={labelConfirmed?"builder-confirm checked":"builder-confirm"}><input type="checkbox" disabled={!customConcentration} checked={labelConfirmed} onChange={event=>setLabelConfirmed(event.target.checked)}/><span><b>Custom concentration matches label</b>Read both values from the physical vial</span></label><button className="continue" disabled={!labelConfirmed||!customConcentration}>Use custom concentration <span>→</span></button></>}</form>}
        {stage==="indication"&&<><h1>Adult analgesia</h1><p className="screen-help">Moderate to severe pain in an adult. Pediatric analgesia is not included in this waiver.</p><button className="builder-confirm checked" onClick={()=>setStage("result")}><span><b>{indication}</b>Auto-filled from waiver 500:62</span></button></>}
        {stage==="route"&&<><h1>IV/IO</h1><p className="screen-help">The waiver lists IV/IO administration. Mix in 50–100 mL NS over 5–10 minutes when conditions allow.</p><button className="builder-confirm checked" onClick={()=>setStage("result")}><span><b>IV/IO</b>Auto-filled route</span></button></>}
        {stage==="patient"&&<><h1>Select adult weight</h1><p className="screen-help">One tap saves the weight and returns to the calculation. Enter a number only when a better weight is known.</p><WeightQuickSelect kind="adult" valueKg={weightKg} onSelect={(kg,source)=>{setWeightKg(kg);setWeightSource(source);setPlannedDose(fmt(kg*doseRate));setSafetyConfirmed(false);setStage("safety")}}/></>}
        {stage==="dose"&&<><h1>Select amount to give</h1><p className="screen-help">The waiver dose is 0.25 mg/kg. The calculated dose is prefilled; a lesser dose may be entered.</p><div className="live-math"><small>PROTOCOL DOSE</small><b>{fmt(protocolDose)} mg</b><span>{fmt(weightKg)} kg × 0.25 mg/kg</span></div><div className="dashboard-dose-editor"><label>Selected dose<input autoFocus inputMode="decimal" value={plannedDose} onChange={event=>setPlannedDose(event.target.value)}/><b>mg</b></label>{!selectedDoseValid&&<span>Enter more than 0 and no more than {fmt(protocolDose)} mg.</span>}<button onClick={()=>setPlannedDose(fmt(protocolDose))}>Use calculated dose</button></div><button className="continue" disabled={!selectedDoseValid} onClick={()=>setStage("safety")}>Use selected dose <span>→</span></button></>}
        {stage==="safety"&&<><h1>Review Ketamine safety</h1><p className="screen-help">Read every item, then confirm the full list once.</p><div className="builder-safety-list">{safetyItems.map((item,index)=><div key={item}><b>{index+1}</b><span>{item}</span></div>)}</div><label className={safetyConfirmed?"builder-confirm checked":"builder-confirm"}><input type="checkbox" checked={safetyConfirmed} onChange={event=>setSafetyConfirmed(event.target.checked)}/><span><b>Confirm all safety checks</b>Every item above is confirmed</span></label><button className="continue" disabled={!safetyConfirmed} onClick={()=>setStage("result")}>Show final dose <span>→</span></button></>}
      </section>}
    </div>
  </main>;
}
