export const DEFAULT_FIELD_MEDICATION_IDS:string[] = [
  "adenosine",
  "albuterol",
  "amiodarone",
  "ondansetron",
  "droperidol",
  "atropine",
  "midazolam",
  "calcium",
  "dextrose",
  "diphenhydramine",
  "epinephrine",
  "ipratropium",
  "magnesium",
  "methylprednisolone",
  "naloxone",
  "nitroglycerin",
  "ketorolac",
  "fentanyl",
  "ketamine",
  "oral-glucose",
  "racemic-epinephrine",
  "sodium-bicarbonate",
];

export const CURRENT_DMP_PROTOCOL_REVISION = "July 2026";
