import type { IScannerControls } from "@zxing/browser";
import {useEffect,useRef,useState} from "react";
type Info={brand_name?:string;generic_name?:string;labeler_name?:string;dosage_form?:string;route?:string[];product_ndc?:string;active_ingredients?:{name:string;strength:string}[];packaging?:{package_ndc:string;description:string}[]};
export type StockVial={drug:"fentanyl"|"midazolam";amount:string;volume:string;unit:"mcg"|"mg";label:string;barcode:string;photo?:string};
export default function MedScanner({onUse}:{onUse:(v:StockVial)=>void}){
 const [open,setOpen]=useState(false),[scanning,setScanning]=useState(false),[raw,setRaw]=useState(""),[lookup,setLookup]=useState(""),[status,setStatus]=useState("Ready to scan."),[info,setInfo]=useState<Info|null>(null),[saved,setSaved]=useState<StockVial|null>(null),[med,setMed]=useState<StockVial["drug"]>("fentanyl"),[amount,setAmount]=useState(""),[volume,setVolume]=useState(""),[label,setLabel]=useState(""),[verified,setVerified]=useState(false),video=useRef<HTMLVideoElement>(null),controls=useRef<IScannerControls|null>(null);
 const stop=()=>{controls.current?.stop();controls.current=null;setScanning(false)};useEffect(()=>()=>stop(),[]);
 const close=()=>{stop();setOpen(false)},process=async(value:string)=>{setRaw(value);setInfo(null);setVerified(false);const local=readVial(value);setSaved(local);if(local){setStatus("Exact barcode matched to this device’s verified stock-vial list.");return}setStatus("Searching medication databases…");const found=await findDrug(value);setInfo(found);if(found){const n=`${found.generic_name||""} ${found.brand_name||""}`.toLowerCase();if(n.includes("midazolam"))setMed("midazolam");if(n.includes("fentanyl"))setMed("fentanyl");setLabel(found.brand_name||found.generic_name||"");setStatus("FDA NDC Directory match found. Verify the physical vial before saving it.")}else setStatus("No reliable public match. Map this exact vial from its physical label below.")};
 const start=async()=>{setStatus("Starting camera…");setScanning(true);try{const {BrowserMultiFormatReader}=await import("@zxing/browser"),reader=new BrowserMultiFormatReader();controls.current=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:"environment"}}},video.current!,async r=>{if(r){stop();await process(r.getText())}})}catch{setScanning(false);setStatus("Camera unavailable or permission denied. Enter the barcode manually.")}};
 const unit=med==="fentanyl"?"mcg":"mg",ok=!!raw&&Number(amount)>0&&Number(volume)>0&&verified,save=()=>{if(!ok)return;const vial:StockVial={drug:med,amount,volume,unit,label:label||med,barcode:raw};localStorage.setItem(key(raw),JSON.stringify(vial));setSaved(vial);onUse(vial);close()};
 const p=parse(raw);
 return <><button className="scan-med" onClick={()=>setOpen(true)}><span className="scan-icon">▦</span><span><small>STOCK VIAL TESTING</small><b>Scan medication barcode</b><em>Identify or map the vial and prefill the workflow</em></span><i>›</i></button>{open&&<div className="modal-backdrop scanner-backdrop"><section className="scanner-modal" role="dialog" aria-modal="true" aria-labelledby="scanner-title"><button className="close" onClick={close} aria-label="Close scanner">×</button><small className="test-label">TEST MODE — VERIFY EVERY RESULT</small><h2 id="scanner-title">Scan a stock medication</h2><p>Scan the individual vial when possible. A carton and vial may have different barcodes.</p><div className={`camera-frame ${scanning?"active":""}`}><video ref={video} muted playsInline/><span>{scanning?"Hold barcode steady":"Camera is off"}</span></div><button className="camera-button" onClick={scanning?stop:start}>{scanning?"Stop camera":"Open camera and scan"}</button><div className="manual-scan"><label>Barcode number or scanner output<input value={lookup} onChange={e=>setLookup(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&lookup.trim())process(lookup.trim())}} placeholder="Enter code if camera cannot scan"/></label><button disabled={!lookup.trim()} onClick={()=>process(lookup.trim())}>Look up</button></div><div className="scan-status" role="status">{status}</div>
 {raw&&<section className="scan-results"><h3>Information available from scan</h3><Result l="Raw barcode" v={raw}/><Result l="Format" v={p.format}/><Result l="GTIN" v={p.gtin}/><Result l="Possible NDC" v={p.ndc}/><Result l="Expiration" v={p.expiration}/><Result l="Lot" v={p.lot}/><Result l="Serial" v={p.serial}/>{info&&<><h3>FDA NDC Directory match</h3><Result l="Brand" v={info.brand_name}/><Result l="Generic" v={info.generic_name}/><Result l="Ingredient / strength" v={info.active_ingredients?.map(x=>`${x.name} ${x.strength}`).join("; ")}/><Result l="Dosage form" v={info.dosage_form}/><Result l="Route" v={info.route?.join(", ")}/><Result l="Labeler" v={info.labeler_name}/><Result l="Product NDC" v={info.product_ndc}/><Result l="Packages" v={info.packaging?.map(x=>`${x.package_ndc}: ${x.description}`).join("; ")}/></>}</section>}
 {saved?<section className="saved-vial"><small>EXACT BARCODE MATCH — SAVED ON THIS DEVICE</small><h3>{saved.label}</h3><b>{saved.amount} {saved.unit} in {saved.volume} mL • {Number(saved.amount)/Number(saved.volume)} {saved.unit}/mL</b><button onClick={()=>{onUse(saved);close()}}>Use this vial and continue</button><p>The physical vial must still be confirmed later.</p></section>:raw&&<section className="map-vial"><small>NO VERIFIED STOCK MATCH</small><h3>Map this exact vial</h3><p>Complete this once from the physical label. It is stored only on this device.</p><label>Medication<select value={med} onChange={e=>{setMed(e.target.value as StockVial["drug"]);setAmount("");setVolume("");setVerified(false)}}><option value="fentanyl">Fentanyl</option><option value="midazolam">Midazolam (Versed)</option></select></label><label>Label or manufacturer<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Optional stock description"/></label><div className="map-concentration"><label>Total drug<input inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setVerified(false)}}/><b>{unit}</b></label><label>Total volume<input inputMode="decimal" value={volume} onChange={e=>{setVolume(e.target.value);setVerified(false)}}/><b>mL</b></label></div>{Number(amount)>0&&Number(volume)>0&&<div className="mapped-strength">Calculated concentration: <b>{Number(amount)/Number(volume)} {unit}/mL</b></div>}<label className={`map-confirm ${verified?"checked":""}`}><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/><span><b>I read the physical vial label</b>Medication, drug amount and vial volume match.</span></label><button className="save-vial" disabled={!ok} onClick={save}>Save barcode and fill workflow</button></section>}
 <div className="scanner-warning"><b>Barcode lookup is not clinical confirmation.</b><span>Stock and manufacturers change. The physical vial check remains required before the final calculation.</span></div></section></div>}</>}
async function findDrug(value:string){for(const c of candidates(value))for(const f of ["packaging.package_ndc","product_ndc"])try{const r=await fetch(`https://api.fda.gov/drug/ndc.json?search=${encodeURIComponent(`${f}:\"${c}\"`)}&limit=1`);if(r.ok){const j=await r.json();if(j.results?.[0])return j.results[0] as Info}}catch{}return null}
function candidates(value:string){const n=digits(parse(value).ndc||value),s=new Set<string>([value]);if(n.length===10){s.add(`${n.slice(0,4)}-${n.slice(4,8)}-${n.slice(8)}`);s.add(`${n.slice(0,5)}-${n.slice(5,8)}-${n.slice(8)}`);s.add(`${n.slice(0,5)}-${n.slice(5,9)}-${n.slice(9)}`)}if(n.length===11){s.add(`${n.slice(0,5)}-${n.slice(5,9)}-${n.slice(9)}`);s.add(`${n.slice(1,5)}-${n.slice(5,9)}-${n.slice(9)}`)}return [...s]}
function key(x:string){return`metroMedDose.stockVial.${btoa(unescape(encodeURIComponent(x))).replace(/=/g,"")}`}function readVial(x:string){try{return JSON.parse(localStorage.getItem(key(x))||"null") as StockVial|null}catch{return null}}function Result({l,v}:{l:string;v?:string}){return v?<div className="scan-result"><span>{l}</span><b>{v}</b></div>:null}function digits(x:string){return x.replace(/\D/g,"")}
function parse(raw:string){const clean=raw.replace(/^]d2/,""),gs=clean.replace(/\u001d/g,"|");let gtin="",expiration="",lot="",serial="";const a=gs.match(/(?:^|\(|\|)01\)?(\d{14})/),e=gs.match(/(?:^|\(|\|)17\)?(\d{6})/),l=gs.match(/(?:^|\(|\|)10\)?([^|()]{1,20})/),s=gs.match(/(?:^|\(|\|)21\)?([^|()]{1,20})/);if(a)gtin=a[1];if(e){const y=+e[1].slice(0,2);expiration=`${e[1].slice(2,4)}/${e[1].slice(4,6)}/${y>=50?1900+y:2000+y}`}if(l)lot=l[1];if(s)serial=s[1];const n=digits(clean);if(!gtin&&n.length===14)gtin=n;return{format:gtin||e||l?"GS1 / pharmaceutical barcode":n.length===12?"UPC-A / linear":"Unclassified",gtin,ndc:gtin?gtin.slice(-11,-1):n.length===10||n.length===11?n:"",expiration,lot,serial}}
