import type { IScannerControls } from "@zxing/browser";
import { useEffect, useRef, useState } from "react";

type DrugResult={brand_name?:string;generic_name?:string;labeler_name?:string;dosage_form?:string;route?:string[];product_ndc?:string;package_ndc?:string;active_ingredients?:{name:string;strength:string}[];packaging?:{package_ndc:string;description:string}[]};

export default function MedScanner(){
 const [open,setOpen]=useState(false),[scanning,setScanning]=useState(false),[raw,setRaw]=useState(""),[status,setStatus]=useState("Ready to scan."),[drug,setDrug]=useState<DrugResult|null>(null),[lookup,setLookup]=useState(""),video=useRef<HTMLVideoElement>(null),controls=useRef<IScannerControls|null>(null);
 const stop=()=>{controls.current?.stop();controls.current=null;setScanning(false)};
 useEffect(()=>()=>stop(),[]);
 const close=()=>{stop();setOpen(false)};
 const start=async()=>{setDrug(null);setStatus("Starting camera…");setScanning(true);try{const {BrowserMultiFormatReader}=await import("@zxing/browser"),reader=new BrowserMultiFormatReader();controls.current=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:"environment"}}},video.current!,async(result)=>{if(!result)return;const value=result.getText();stop();setRaw(value);setStatus("Barcode captured. Looking up available drug information…");await findDrug(value)});}catch{setScanning(false);setStatus("Camera scanning is unavailable or permission was denied. Enter the barcode number below.")}};
 const findDrug=async(value:string)=>{setDrug(null);const parsed=parseBarcode(value),candidates=[parsed.ndc,parsed.gtin?.slice(1,-1),digits(value)].filter(Boolean) as string[];for(const candidate of [...new Set(candidates)]){for(const field of ["package_ndc","product_ndc"]){try{const q=encodeURIComponent(`${field}:\"${candidate}\"`),res=await fetch(`https://api.fda.gov/drug/ndc.json?search=${q}&limit=1`);if(!res.ok)continue;const json=await res.json();if(json.results?.[0]){setDrug(json.results[0]);setStatus("FDA NDC Directory match found.");return}}catch{/* Continue through lookup candidates. */}}}setStatus("No exact FDA NDC Directory match was found. The scanned information is shown below for inventory testing.")};
 const submit=async()=>{const value=lookup.trim();if(!value)return;setRaw(value);setStatus("Looking up available drug information…");await findDrug(value)};
 const parsed=parseBarcode(raw);
 return <><button className="scan-med" onClick={()=>setOpen(true)}><span className="scan-icon">▦</span><span><small>STOCK VIAL TESTING</small><b>Scan medication barcode</b><em>See everything the vial barcode makes available</em></span><i>›</i></button>{open&&<div className="modal-backdrop scanner-backdrop"><section className="scanner-modal" role="dialog" aria-modal="true" aria-labelledby="scanner-title"><button className="close" aria-label="Close scanner" onClick={close}>×</button><small className="test-label">TEST MODE — NOT FOR MEDICATION ADMINISTRATION</small><h2 id="scanner-title">Scan a stock medication</h2><p>Center the vial or package barcode in the camera. This test does not select a drug or confirm a concentration.</p><div className={`camera-frame ${scanning?"active":""}`}><video ref={video} muted playsInline/><span>{scanning?"Hold barcode steady":"Camera is off"}</span></div><button className="camera-button" onClick={scanning?stop:start}>{scanning?"Stop camera":"Open camera and scan"}</button><div className="manual-scan"><label>Barcode number or scanner output<input inputMode="text" value={lookup} onChange={e=>setLookup(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")submit()}} placeholder="Enter code if camera cannot scan"/></label><button disabled={!lookup.trim()} onClick={submit}>Look up</button></div><div className="scan-status" role="status">{status}</div>{raw&&<section className="scan-results"><h3>Information available from scan</h3><Result label="Raw barcode data" value={raw}/><Result label="Format detected" value={parsed.format}/>{parsed.gtin&&<Result label="GTIN" value={parsed.gtin}/>} {parsed.ndc&&<Result label="Possible NDC" value={parsed.ndc}/>} {parsed.expiration&&<Result label="Encoded expiration" value={parsed.expiration}/>} {parsed.lot&&<Result label="Encoded lot" value={parsed.lot}/>} {parsed.serial&&<Result label="Encoded serial" value={parsed.serial}/>} {drug?<><h3>FDA NDC Directory match</h3><Result label="Brand name" value={drug.brand_name}/><Result label="Generic name" value={drug.generic_name}/><Result label="Active ingredient / strength" value={drug.active_ingredients?.map(x=>`${x.name} ${x.strength}`).join("; ")}/><Result label="Dosage form" value={drug.dosage_form}/><Result label="Route" value={drug.route?.join(", ")}/><Result label="Labeler" value={drug.labeler_name}/><Result label="Product NDC" value={drug.product_ndc}/><Result label="Package NDC" value={drug.package_ndc||drug.packaging?.map(x=>x.package_ndc).join(", ")}/></>:<div className="no-fda-match">Drug name and concentration are not safely identifiable from this scan alone.</div>}</section>}<div className="scanner-warning"><b>Always read the physical vial label.</b><span>A successful scan is an inventory test only. Barcode content and FDA directory records must be validated against your department’s exact manufacturers and concentrations before any future clinical use.</span></div></section></div>}</>
}

function Result({label,value}:{label:string;value?:string}){if(!value)return null;return <div className="scan-result"><span>{label}</span><b>{value}</b></div>}
function digits(x:string){return x.replace(/\D/g,"")}
function parseBarcode(raw:string){const clean=raw.replace(/^]d2/,""),gs=clean.replace(/\u001d/g,"|");let gtin="",expiration="",lot="",serial="";const ai01=gs.match(/(?:^|\(|\|)01\)?(\d{14})/),ai17=gs.match(/(?:^|\(|\|)17\)?(\d{6})/),ai10=gs.match(/(?:^|\(|\|)10\)?([^|()]{1,20})/),ai21=gs.match(/(?:^|\(|\|)21\)?([^|()]{1,20})/);if(ai01)gtin=ai01[1];if(ai17){const y=Number(ai17[1].slice(0,2)),m=ai17[1].slice(2,4),d=ai17[1].slice(4,6);expiration=`${m}/${d}/${y>=50?1900+y:2000+y}`;}if(ai10)lot=ai10[1];if(ai21)serial=ai21[1];const numeric=digits(clean);if(!gtin&&numeric.length===14)gtin=numeric;const possibleNdc=gtin?gtin.slice(1,-1):numeric.length===10?numeric:"";return{format:gtin||ai17||ai10?"GS1 / pharmaceutical barcode":numeric.length===12?"UPC-A or linear barcode":"Unclassified barcode data",gtin,ndc:possibleNdc,expiration,lot,serial}}
